
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Dec 13 2024 13:07:44 IST (Dec 13 2024 07:37:44 UTC)

// Verification Directory fv/prefix_adder_32bit 

module prefix_adder_32bit(clk, A, B, Cin, Sum, Cout);
  input clk, Cin;
  input [31:0] A, B;
  output [31:0] Sum;
  output Cout;
  wire clk, Cin;
  wire [31:0] A, B;
  wire [31:0] Sum;
  wire Cout;
  wire [31:0] A_ff;
  wire [31:0] B_ff;
  wire [31:0] C;
  wire Cin_ff, n_1, n_3, n_6, n_7, n_8, n_9, n_10;
  wire n_11, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_20, n_21, n_22, n_23, n_24, n_25, n_26, n_27;
  wire n_28, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_36, n_37, n_38, n_39, n_40, n_41, n_42, n_43;
  wire n_46, n_47, n_48, n_49, n_50, n_51, n_52, n_53;
  wire n_54, n_55, n_56, n_57, n_58, n_59, n_60, n_61;
  wire n_62, n_63, n_64, n_65, n_66, n_67, n_68, n_69;
  wire n_70, n_71, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_83, n_84, n_85, n_86;
  wire n_87, n_88, n_89, n_90, n_91, n_92, n_93, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_103, n_104;
  wire n_105, n_106, n_107, n_108, n_109, n_110, n_111, n_112;
  wire n_113, n_114, n_115, n_116, n_117, n_118, n_120, n_121;
  wire n_122, n_123, n_124, n_126, n_127, n_128, n_129, n_130;
  wire n_131, n_132, n_133, n_134, n_135, n_136, n_137, n_138;
  wire n_139, n_206, n_207, n_208, n_209, n_210, n_211;
  DFFHQX1 \Sum_reg[11] (.CK (clk), .D (n_139), .Q (Sum[11]));
  DFFHQX1 \Sum_reg[9] (.CK (clk), .D (n_138), .Q (Sum[9]));
  SDFFQXL \Sum_reg[7] (.CK (clk), .D (n_132), .SI (n_133), .SE (n_107),
       .Q (Sum[7]));
  MXI2X1 g2943(.A (n_137), .B (n_136), .S0 (n_206), .Y (n_139));
  MXI2XL g2942(.A (n_135), .B (n_134), .S0 (n_113), .Y (n_138));
  SDFFQXL \Sum_reg[10] (.CK (clk), .D (n_130), .SI (n_131), .SE (n_15),
       .Q (Sum[10]));
  SDFFQXL \Sum_reg[5] (.CK (clk), .D (n_127), .SI (n_126), .SE (n_67),
       .Q (Sum[5]));
  CLKINVX1 g2949(.A (n_136), .Y (n_137));
  CLKINVX1 g2950(.A (n_134), .Y (n_135));
  INVXL g2947(.A (n_132), .Y (n_133));
  NAND2X1 g2951(.A (n_114), .B (n_129), .Y (n_136));
  OAI21X1 g2952(.A0 (n_85), .A1 (n_123), .B0 (n_108), .Y (n_134));
  SDFFQXL \Sum_reg[8] (.CK (clk), .D (n_121), .SI (n_122), .SE (n_68),
       .Q (Sum[8]));
  SDFFQXL \Sum_reg[6] (.CK (clk), .D (n_110), .SI (n_76), .SE (n_128),
       .Q (Sum[6]));
  OAI21X1 g2948(.A0 (n_81), .A1 (n_210), .B0 (n_98), .Y (n_132));
  INVXL g2955(.A (n_130), .Y (n_131));
  NAND2XL g2956(.A (n_88), .B (n_128), .Y (n_129));
  CLKINVX1 g2958(.A (n_126), .Y (n_127));
  OAI2BB1X1 g2957(.A0N (n_124), .A1N (n_115), .B0 (n_117), .Y (n_130));
  NOR2XL g2960(.A (n_116), .B (n_124), .Y (n_126));
  CLKINVX1 g2962(.A (n_128), .Y (n_123));
  SDFFQXL \Sum_reg[4] (.CK (clk), .D (n_112), .SI (n_120), .SE (n_80),
       .Q (Sum[4]));
  INVXL g2961(.A (n_121), .Y (n_122));
  NAND2X1 g2964(.A (n_211), .B (n_118), .Y (n_128));
  NAND2XL g2963(.A (n_104), .B (n_111), .Y (n_121));
  NOR2XL g2966(.A (n_109), .B (n_120), .Y (n_124));
  AOI21X1 g2971(.A0 (n_116), .A1 (n_115), .B0 (n_106), .Y (n_117));
  AOI22X1 g2969(.A0 (n_113), .A1 (n_100), .B0 (A_ff[9]), .B1 (B_ff[9]),
       .Y (n_114));
  NAND2X1 g2970(.A (n_74), .B (n_112), .Y (n_118));
  CLKINVX1 g2973(.A (n_112), .Y (n_120));
  AOI221X1 g2974(.A0 (n_83), .A1 (n_101), .B0 (n_110), .B1 (n_105), .C0
       (n_95), .Y (n_111));
  SDFFQXL \Sum_reg[3] (.CK (clk), .D (n_109), .SI (n_209), .SE (n_103),
       .Q (Sum[3]));
  AOI21X1 g2979(.A0 (n_107), .A1 (n_87), .B0 (n_69), .Y (n_108));
  NAND3X2 g2975(.A (n_82), .B (n_65), .C (n_91), .Y (n_112));
  OAI2BB1X1 g2980(.A0N (n_105), .A1N (n_77), .B0 (n_96), .Y (n_106));
  NAND4BXL g2968(.AN (n_103), .B (n_209), .C (n_92), .D (n_101), .Y
       (n_104));
  NOR2XL g2986(.A (n_99), .B (n_97), .Y (n_115));
  OAI21X1 g2977(.A0 (n_99), .A1 (n_86), .B0 (n_79), .Y (n_100));
  INVXL g3005(.A (n_105), .Y (n_98));
  CLKINVX1 g3004(.A (n_101), .Y (n_97));
  AOI21X1 g2984(.A0 (n_95), .A1 (n_66), .B0 (n_78), .Y (n_96));
  DFFQXL Cout_reg(.CK (clk), .D (n_73), .Q (Cout));
  DFFQXL \Sum_reg[0] (.CK (clk), .D (n_75), .Q (Sum[0]));
  SDFFQXL \Sum_reg[2] (.CK (clk), .D (n_92), .SI (n_63), .SE (n_89), .Q
       (Sum[2]));
  SDFFQXL \Sum_reg[31] (.CK (clk), .D (n_208), .SI (n_61), .SE (C[30]),
       .Q (Sum[31]));
  SDFFQXL \Sum_reg[1] (.CK (clk), .D (n_90), .SI (n_62), .SE (Cin_ff),
       .Q (Sum[1]));
  SDFFQXL \Sum_reg[23] (.CK (clk), .D (n_36), .SI (n_37), .SE (C[22]),
       .Q (Sum[23]));
  SDFFQXL \Sum_reg[14] (.CK (clk), .D (n_50), .SI (n_51), .SE (C[13]),
       .Q (Sum[14]));
  NAND3X1 g2978(.A (n_90), .B (n_89), .C (n_92), .Y (n_91));
  NOR3BX1 g2985(.AN (n_113), .B (n_84), .C (n_99), .Y (n_88));
  INVXL g3002(.A (n_86), .Y (n_87));
  NAND2BX1 g3012(.AN (n_84), .B (n_107), .Y (n_85));
  OAI21X1 g3014(.A0 (n_82), .A1 (n_109), .B0 (n_71), .Y (n_83));
  SDFFQXL \Sum_reg[12] (.CK (clk), .D (n_54), .SI (n_55), .SE (C[11]),
       .Q (Sum[12]));
  SDFFQXL \Sum_reg[25] (.CK (clk), .D (n_20), .SI (n_21), .SE (C[24]),
       .Q (Sum[25]));
  SDFFQXL \Sum_reg[28] (.CK (clk), .D (n_26), .SI (n_27), .SE (C[27]),
       .Q (Sum[28]));
  SDFFQXL \Sum_reg[24] (.CK (clk), .D (n_34), .SI (n_35), .SE (C[23]),
       .Q (Sum[24]));
  SDFFQXL \Sum_reg[15] (.CK (clk), .D (n_48), .SI (n_49), .SE (C[14]),
       .Q (Sum[15]));
  AOI21X1 g2972(.A0 (n_90), .A1 (n_89), .B0 (n_64), .Y (n_103));
  SDFFQXL \Sum_reg[26] (.CK (clk), .D (n_30), .SI (n_31), .SE (C[25]),
       .Q (Sum[26]));
  SDFFQXL \Sum_reg[22] (.CK (clk), .D (n_40), .SI (n_41), .SE (C[21]),
       .Q (Sum[22]));
  SDFFQXL \Sum_reg[21] (.CK (clk), .D (n_32), .SI (n_33), .SE (C[20]),
       .Q (Sum[21]));
  SDFFQXL \Sum_reg[30] (.CK (clk), .D (n_24), .SI (n_25), .SE (C[29]),
       .Q (Sum[30]));
  SDFFQXL \Sum_reg[29] (.CK (clk), .D (n_22), .SI (n_23), .SE (C[28]),
       .Q (Sum[29]));
  SDFFQXL \Sum_reg[20] (.CK (clk), .D (n_38), .SI (n_39), .SE (C[19]),
       .Q (Sum[20]));
  SDFFQXL \Sum_reg[16] (.CK (clk), .D (n_46), .SI (n_47), .SE (C[15]),
       .Q (Sum[16]));
  SDFFQXL \Sum_reg[18] (.CK (clk), .D (n_58), .SI (n_59), .SE (C[17]),
       .Q (Sum[18]));
  SDFFQXL \Sum_reg[17] (.CK (clk), .D (n_56), .SI (n_57), .SE (C[16]),
       .Q (Sum[17]));
  SDFFQXL \Sum_reg[19] (.CK (clk), .D (n_42), .SI (n_43), .SE (C[18]),
       .Q (Sum[19]));
  SDFFQXL \Sum_reg[27] (.CK (clk), .D (n_28), .SI (n_29), .SE (C[26]),
       .Q (Sum[27]));
  SDFFQXL \Sum_reg[13] (.CK (clk), .D (n_52), .SI (n_53), .SE (C[12]),
       .Q (Sum[13]));
  OAI21X1 g3019(.A0 (n_18), .A1 (n_81), .B0 (n_16), .Y (n_105));
  NOR2BX2 g3018(.AN (n_80), .B (n_84), .Y (n_101));
  INVXL g3003(.A (n_78), .Y (n_79));
  NOR2XL g3006(.A (n_76), .B (n_99), .Y (n_77));
  MXI2XL g3011(.A (n_60), .B (Cin_ff), .S0 (n_207), .Y (n_75));
  NOR2XL g3024(.A (n_109), .B (n_70), .Y (n_74));
  AO22X1 g3015(.A0 (C[31]), .A1 (n_208), .B0 (B_ff[31]), .B1
       (A_ff[31]), .Y (n_73));
  NOR2XL g3025(.A (n_71), .B (n_70), .Y (n_93));
  AOI21X1 g3016(.A0 (n_17), .A1 (n_110), .B0 (n_95), .Y (n_86));
  OAI2BB1X1 g3017(.A0N (n_69), .A1N (n_68), .B0 (n_10), .Y (n_78));
  NAND2X2 g3026(.A (n_67), .B (n_110), .Y (n_84));
  INVXL g3021(.A (n_99), .Y (n_66));
  NAND2XL g3022(.A (n_64), .B (n_92), .Y (n_65));
  INVXL g3029(.A (n_92), .Y (n_63));
  INVXL g3028(.A (n_90), .Y (n_62));
  INVXL g3027(.A (n_208), .Y (n_61));
  CLKINVX1 g3030(.A (n_209), .Y (n_109));
  CLKINVX1 g3036(.A (n_110), .Y (n_76));
  CLKINVX1 g3034(.A (n_67), .Y (n_81));
  CLKINVX1 g3032(.A (n_80), .Y (n_70));
  OAI21X2 g3020(.A0 (n_60), .A1 (n_11), .B0 (n_9), .Y (n_89));
  NAND2X2 g3023(.A (n_107), .B (n_68), .Y (n_99));
  INVXL g3038(.A (n_58), .Y (n_59));
  INVXL g3039(.A (n_56), .Y (n_57));
  INVXL g3040(.A (n_54), .Y (n_55));
  INVXL g3041(.A (n_52), .Y (n_53));
  INVXL g3042(.A (n_50), .Y (n_51));
  INVXL g3043(.A (n_48), .Y (n_49));
  INVXL g3044(.A (n_46), .Y (n_47));
  INVXL g3037(.A (n_42), .Y (n_43));
  MXI2X1 g3060(.A (n_8), .B (A_ff[4]), .S0 (B_ff[4]), .Y (n_80));
  MXI2X1 g3057(.A (n_14), .B (A_ff[1]), .S0 (B_ff[1]), .Y (n_90));
  OAI22X2 g3059(.A0 (B_ff[2]), .A1 (n_7), .B0 (A_ff[2]), .B1 (n_1), .Y
       (n_92));
  INVXL g3062(.A (n_40), .Y (n_41));
  INVXL g3063(.A (n_38), .Y (n_39));
  INVXL g3064(.A (n_36), .Y (n_37));
  INVXL g3065(.A (n_34), .Y (n_35));
  INVXL g3066(.A (n_32), .Y (n_33));
  INVXL g3067(.A (n_30), .Y (n_31));
  INVXL g3068(.A (n_28), .Y (n_29));
  INVXL g3069(.A (n_26), .Y (n_27));
  INVXL g3070(.A (n_24), .Y (n_25));
  INVXL g3071(.A (n_22), .Y (n_23));
  INVXL g3061(.A (n_20), .Y (n_21));
  OAI22X2 g3084(.A0 (B_ff[5]), .A1 (n_3), .B0 (A_ff[5]), .B1 (n_6), .Y
       (n_67));
  OAI22X2 g3087(.A0 (B_ff[6]), .A1 (n_13), .B0 (A_ff[6]), .B1 (n_12),
       .Y (n_110));
  INVXL g3035(.A (n_16), .Y (n_17));
  CLKXOR2X1 g3047(.A (A_ff[10]), .B (B_ff[10]), .Y (n_15));
  CLKXOR2X1 g3055(.A (A_ff[16]), .B (B_ff[16]), .Y (n_46));
  CLKINVX1 g3031(.A (n_71), .Y (n_116));
  CLKXOR2X1 g3045(.A (A_ff[19]), .B (B_ff[19]), .Y (n_42));
  CLKXOR2X1 g3046(.A (A_ff[18]), .B (B_ff[18]), .Y (n_58));
  NOR2BX1 g3093(.AN (B_ff[1]), .B (n_14), .Y (n_64));
  CLKXOR2X1 g3048(.A (A_ff[17]), .B (B_ff[17]), .Y (n_56));
  CLKXOR2X1 g3050(.A (A_ff[12]), .B (B_ff[12]), .Y (n_54));
  CLKXOR2X1 g3051(.A (A_ff[13]), .B (B_ff[13]), .Y (n_52));
  CLKXOR2X1 g3052(.A (A_ff[14]), .B (B_ff[14]), .Y (n_50));
  CLKXOR2X1 g3054(.A (A_ff[15]), .B (B_ff[15]), .Y (n_48));
  NOR2XL g3096(.A (n_13), .B (n_12), .Y (n_95));
  CLKXOR2X1 g3078(.A (A_ff[26]), .B (B_ff[26]), .Y (n_30));
  CLKXOR2X1 g3072(.A (A_ff[25]), .B (B_ff[25]), .Y (n_20));
  CLKXOR2X1 g3077(.A (A_ff[21]), .B (B_ff[21]), .Y (n_32));
  CLKXOR2X1 g3073(.A (A_ff[22]), .B (B_ff[22]), .Y (n_40));
  CLKXOR2X1 g3074(.A (A_ff[20]), .B (B_ff[20]), .Y (n_38));
  CLKXOR2X1 g3075(.A (A_ff[23]), .B (B_ff[23]), .Y (n_36));
  CLKXOR2X1 g3076(.A (A_ff[24]), .B (B_ff[24]), .Y (n_34));
  CLKXOR2X1 g3079(.A (A_ff[27]), .B (B_ff[27]), .Y (n_28));
  CLKXOR2X1 g3080(.A (A_ff[28]), .B (B_ff[28]), .Y (n_26));
  CLKXOR2X1 g3081(.A (A_ff[30]), .B (B_ff[30]), .Y (n_24));
  CLKXOR2X1 g3082(.A (A_ff[29]), .B (B_ff[29]), .Y (n_22));
  CLKXOR2X1 g3058(.A (A_ff[9]), .B (B_ff[9]), .Y (n_113));
  CLKXOR2X1 g3083(.A (A_ff[8]), .B (B_ff[8]), .Y (n_68));
  CLKXOR2X2 g3085(.A (A_ff[7]), .B (B_ff[7]), .Y (n_107));
  NOR2X1 g3090(.A (A_ff[0]), .B (B_ff[0]), .Y (n_11));
  NAND2XL g3089(.A (A_ff[8]), .B (B_ff[8]), .Y (n_10));
  NAND2X1 g3088(.A (A_ff[0]), .B (B_ff[0]), .Y (n_9));
  AND2X1 g3091(.A (B_ff[7]), .B (A_ff[7]), .Y (n_69));
  NAND2XL g3095(.A (A_ff[5]), .B (B_ff[5]), .Y (n_16));
  NAND2XL g3094(.A (A_ff[2]), .B (B_ff[2]), .Y (n_82));
  NAND2XL g3092(.A (A_ff[4]), .B (B_ff[4]), .Y (n_18));
  NAND2XL g3097(.A (A_ff[3]), .B (B_ff[3]), .Y (n_71));
  CLKINVX1 g3141(.A (A_ff[4]), .Y (n_8));
  CLKINVX1 g3098(.A (A_ff[2]), .Y (n_7));
  CLKINVX1 g3099(.A (B_ff[5]), .Y (n_6));
  CLKINVX1 g3100(.A (B_ff[6]), .Y (n_12));
  CLKINVX1 g3140(.A (A_ff[5]), .Y (n_3));
  CLKINVX1 g3136(.A (B_ff[2]), .Y (n_1));
  CLKINVX1 g3139(.A (A_ff[6]), .Y (n_13));
  CLKINVX1 g3137(.A (A_ff[1]), .Y (n_14));
  CLKINVX1 g3142(.A (Cin_ff), .Y (n_60));
  DFFQXL \A_ff_reg[30] (.CK (clk), .D (A[30]), .Q (A_ff[30]));
  DFFQXL \A_ff_reg[24] (.CK (clk), .D (A[24]), .Q (A_ff[24]));
  DFFQXL \A_ff_reg[16] (.CK (clk), .D (A[16]), .Q (A_ff[16]));
  DFFQX1 \B_ff_reg[17] (.CK (clk), .D (B[17]), .Q (B_ff[17]));
  DFFQXL \A_ff_reg[29] (.CK (clk), .D (A[29]), .Q (A_ff[29]));
  DFFQX1 \B_ff_reg[25] (.CK (clk), .D (B[25]), .Q (B_ff[25]));
  DFFQX1 \B_ff_reg[23] (.CK (clk), .D (B[23]), .Q (B_ff[23]));
  DFFQX1 \B_ff_reg[10] (.CK (clk), .D (B[10]), .Q (B_ff[10]));
  DFFQXL \A_ff_reg[27] (.CK (clk), .D (A[27]), .Q (A_ff[27]));
  DFFQX1 \B_ff_reg[11] (.CK (clk), .D (B[11]), .Q (B_ff[11]));
  DFFQX1 \B_ff_reg[12] (.CK (clk), .D (B[12]), .Q (B_ff[12]));
  DFFQXL \A_ff_reg[20] (.CK (clk), .D (A[20]), .Q (A_ff[20]));
  DFFQX1 \B_ff_reg[15] (.CK (clk), .D (B[15]), .Q (B_ff[15]));
  DFFQXL \A_ff_reg[10] (.CK (clk), .D (A[10]), .Q (A_ff[10]));
  DFFQX1 \B_ff_reg[19] (.CK (clk), .D (B[19]), .Q (B_ff[19]));
  DFFQXL \A_ff_reg[25] (.CK (clk), .D (A[25]), .Q (A_ff[25]));
  DFFQXL \A_ff_reg[28] (.CK (clk), .D (A[28]), .Q (A_ff[28]));
  DFFQXL \A_ff_reg[12] (.CK (clk), .D (A[12]), .Q (A_ff[12]));
  DFFQXL \A_ff_reg[15] (.CK (clk), .D (A[15]), .Q (A_ff[15]));
  DFFQXL \A_ff_reg[26] (.CK (clk), .D (A[26]), .Q (A_ff[26]));
  DFFQXL \A_ff_reg[13] (.CK (clk), .D (A[13]), .Q (A_ff[13]));
  DFFQX1 \B_ff_reg[13] (.CK (clk), .D (B[13]), .Q (B_ff[13]));
  DFFQXL \A_ff_reg[17] (.CK (clk), .D (A[17]), .Q (A_ff[17]));
  DFFQX1 \B_ff_reg[28] (.CK (clk), .D (B[28]), .Q (B_ff[28]));
  DFFQX1 \B_ff_reg[26] (.CK (clk), .D (B[26]), .Q (B_ff[26]));
  DFFQX1 \B_ff_reg[24] (.CK (clk), .D (B[24]), .Q (B_ff[24]));
  DFFQX1 \B_ff_reg[22] (.CK (clk), .D (B[22]), .Q (B_ff[22]));
  DFFQXL \A_ff_reg[23] (.CK (clk), .D (A[23]), .Q (A_ff[23]));
  DFFQX1 \B_ff_reg[6] (.CK (clk), .D (B[6]), .Q (B_ff[6]));
  DFFQX1 \B_ff_reg[9] (.CK (clk), .D (B[9]), .Q (B_ff[9]));
  DFFQX1 \B_ff_reg[8] (.CK (clk), .D (B[8]), .Q (B_ff[8]));
  DFFQX1 \A_ff_reg[11] (.CK (clk), .D (A[11]), .Q (A_ff[11]));
  DFFQX1 \B_ff_reg[5] (.CK (clk), .D (B[5]), .Q (B_ff[5]));
  DFFQX1 \A_ff_reg[31] (.CK (clk), .D (A[31]), .Q (A_ff[31]));
  DFFQX2 \A_ff_reg[2] (.CK (clk), .D (A[2]), .Q (A_ff[2]));
  DFFQX1 \A_ff_reg[0] (.CK (clk), .D (A[0]), .Q (A_ff[0]));
  DFFQXL \A_ff_reg[14] (.CK (clk), .D (A[14]), .Q (A_ff[14]));
  DFFQX1 \B_ff_reg[21] (.CK (clk), .D (B[21]), .Q (B_ff[21]));
  DFFQX1 \B_ff_reg[30] (.CK (clk), .D (B[30]), .Q (B_ff[30]));
  DFFQX1 \B_ff_reg[18] (.CK (clk), .D (B[18]), .Q (B_ff[18]));
  DFFQX1 \B_ff_reg[29] (.CK (clk), .D (B[29]), .Q (B_ff[29]));
  DFFQX1 \B_ff_reg[20] (.CK (clk), .D (B[20]), .Q (B_ff[20]));
  DFFQXL \A_ff_reg[21] (.CK (clk), .D (A[21]), .Q (A_ff[21]));
  DFFQX1 \B_ff_reg[14] (.CK (clk), .D (B[14]), .Q (B_ff[14]));
  DFFQXL \A_ff_reg[18] (.CK (clk), .D (A[18]), .Q (A_ff[18]));
  DFFQX1 \B_ff_reg[27] (.CK (clk), .D (B[27]), .Q (B_ff[27]));
  DFFQXL \A_ff_reg[22] (.CK (clk), .D (A[22]), .Q (A_ff[22]));
  DFFQXL \A_ff_reg[19] (.CK (clk), .D (A[19]), .Q (A_ff[19]));
  DFFQX1 \B_ff_reg[16] (.CK (clk), .D (B[16]), .Q (B_ff[16]));
  DFFQX1 \B_ff_reg[31] (.CK (clk), .D (B[31]), .Q (B_ff[31]));
  DFFQX2 \A_ff_reg[1] (.CK (clk), .D (A[1]), .Q (A_ff[1]));
  DFFQX1 \B_ff_reg[4] (.CK (clk), .D (B[4]), .Q (B_ff[4]));
  DFFQX1 \B_ff_reg[3] (.CK (clk), .D (B[3]), .Q (B_ff[3]));
  DFFQX1 \B_ff_reg[1] (.CK (clk), .D (B[1]), .Q (B_ff[1]));
  DFFQX1 \B_ff_reg[7] (.CK (clk), .D (B[7]), .Q (B_ff[7]));
  DFFQX2 \A_ff_reg[6] (.CK (clk), .D (A[6]), .Q (A_ff[6]));
  DFFQX1 \A_ff_reg[9] (.CK (clk), .D (A[9]), .Q (A_ff[9]));
  DFFQX1 \A_ff_reg[7] (.CK (clk), .D (A[7]), .Q (A_ff[7]));
  DFFQX1 \A_ff_reg[8] (.CK (clk), .D (A[8]), .Q (A_ff[8]));
  DFFQX1 \A_ff_reg[4] (.CK (clk), .D (A[4]), .Q (A_ff[4]));
  DFFQX2 \B_ff_reg[2] (.CK (clk), .D (B[2]), .Q (B_ff[2]));
  DFFQX2 \B_ff_reg[0] (.CK (clk), .D (B[0]), .Q (B_ff[0]));
  DFFQX1 Cin_ff_reg(.CK (clk), .D (Cin), .Q (Cin_ff));
  DFFQX1 \A_ff_reg[3] (.CK (clk), .D (A[3]), .Q (A_ff[3]));
  DFFQX2 \A_ff_reg[5] (.CK (clk), .D (A[5]), .Q (A_ff[5]));
  CLKXOR2X1 g2(.A (A_ff[11]), .B (B_ff[11]), .Y (n_206));
  CLKXOR2X1 g3274(.A (A_ff[0]), .B (B_ff[0]), .Y (n_207));
  CLKXOR2X1 g3275(.A (A_ff[31]), .B (B_ff[31]), .Y (n_208));
  CLKXOR2X1 g3276(.A (A_ff[3]), .B (B_ff[3]), .Y (n_209));
  NOR2BX1 g3277(.AN (n_118), .B (n_93), .Y (n_210));
  NOR2BXL g3278(.AN (n_18), .B (n_93), .Y (n_211));
endmodule

