
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Dec 13 2024 13:02:54 IST (Dec 13 2024 07:32:54 UTC)

// Verification Directory fv/prefix_adder_16bit 

module prefix_adder_16bit(clk, A, B, Cin, Sum, Cout);
  input clk, Cin;
  input [15:0] A, B;
  output [15:0] Sum;
  output Cout;
  wire clk, Cin;
  wire [15:0] A, B;
  wire [15:0] Sum;
  wire Cout;
  wire [15:0] C;
  wire [15:0] B_ff;
  wire [15:0] A_ff;
  wire Cin_ff, n_0, n_2, n_3, n_4, n_5, n_7, n_8;
  wire n_9, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_24, n_25, n_26, n_27;
  wire n_30, n_31, n_32, n_33, n_34, n_35, n_36, n_37;
  wire n_38, n_39, n_40, n_41, n_42, n_43, n_44, n_45;
  wire n_46, n_47, n_48, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_71, n_72;
  wire n_73, n_74, n_75, n_76, n_78, n_79, n_80, n_81;
  wire n_82, n_84, n_85, n_86, n_87, n_88, n_89, n_90;
  wire n_91, n_92, n_93, n_95, n_96, n_97, n_98, n_100;
  wire n_101, n_102, n_103, n_104, n_106, n_107, n_108, n_109;
  wire n_110, n_111, n_112, n_113, n_114, n_115, n_117, n_118;
  wire n_119, n_120, n_121, n_122, n_123, n_124, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_134, n_135, n_136;
  wire n_137, n_172, n_173, n_174, n_175, n_176, n_177, n_178;
  wire n_179, n_180;
  DFFHQX1 \Sum_reg[12] (.CK (clk), .D (n_137), .Q (Sum[12]));
  SDFFQXL \Sum_reg[10] (.CK (clk), .D (n_134), .SI (n_135), .SE
       (n_104), .Q (Sum[10]));
  DFFHQX1 \Sum_reg[9] (.CK (clk), .D (n_136), .Q (Sum[9]));
  SDFFQXL \Sum_reg[11] (.CK (clk), .D (n_127), .SI (n_128), .SE (n_19),
       .Q (Sum[11]));
  MXI2X1 g4121(.A (n_132), .B (n_131), .S0 (n_173), .Y (n_137));
  MXI2XL g4122(.A (n_130), .B (n_129), .S0 (n_31), .Y (n_136));
  DFFQXL \Sum_reg[6] (.CK (clk), .D (n_172), .Q (Sum[6]));
  MDFFHQX1 \Sum_reg[7] (.CK (clk), .D0 (n_122), .D1 (n_123), .S0
       (n_41), .Q (Sum[7]));
  SDFFQXL \Sum_reg[8] (.CK (clk), .D (n_106), .SI (n_74), .SE (n_121),
       .Q (Sum[8]));
  INVXL g4130(.A (n_134), .Y (n_135));
  CLKINVX1 g4132(.A (n_131), .Y (n_132));
  SDFFQXL \Sum_reg[5] (.CK (clk), .D (n_36), .SI (n_69), .SE (n_113),
       .Q (Sum[5]));
  CLKINVX1 g4131(.A (n_129), .Y (n_130));
  INVXL g4136(.A (n_127), .Y (n_128));
  OAI2BB1X1 g4135(.A0N (n_90), .A1N (n_114), .B0 (n_126), .Y (n_131));
  NAND3X1 g4133(.A (n_103), .B (n_107), .C (n_118), .Y (n_134));
  NOR2XL g4138(.A (n_109), .B (n_119), .Y (n_127));
  NOR2X1 g4134(.A (n_117), .B (n_115), .Y (n_129));
  NOR2XL g4141(.A (n_177), .B (n_111), .Y (n_126));
  SDFFQXL \Sum_reg[4] (.CK (clk), .D (n_45), .SI (n_56), .SE (n_120),
       .Q (Sum[4]));
  INVXL g4126(.A (n_122), .Y (n_123));
  NAND3X1 g4139(.A (n_97), .B (n_101), .C (n_95), .Y (n_121));
  OAI21X1 g4128(.A0 (n_68), .A1 (n_120), .B0 (n_71), .Y (n_124));
  OAI21X1 g4129(.A0 (n_73), .A1 (n_120), .B0 (n_180), .Y (n_122));
  NOR2XL g4145(.A (n_78), .B (n_110), .Y (n_119));
  SDFFQXL \Sum_reg[3] (.CK (clk), .D (n_46), .SI (n_40), .SE (n_112),
       .Q (Sum[3]));
  OAI21X1 g4140(.A0 (n_61), .A1 (n_175), .B0 (n_75), .Y (n_118));
  OAI21X1 g4148(.A0 (n_108), .A1 (n_180), .B0 (n_79), .Y (n_117));
  NOR2XL g4137(.A (n_88), .B (n_120), .Y (n_115));
  NAND2XL g4158(.A (n_66), .B (n_180), .Y (n_114));
  OAI21X1 g4142(.A0 (n_98), .A1 (n_112), .B0 (n_62), .Y (n_113));
  NOR3X1 g4146(.A (n_63), .B (n_89), .C (n_112), .Y (n_111));
  AOI211X1 g4151(.A0 (n_100), .A1 (n_102), .B0 (n_178), .C0 (n_85), .Y
       (n_110));
  OAI31XL g4155(.A0 (n_57), .A1 (n_38), .A2 (n_108), .B0 (n_87), .Y
       (n_109));
  NAND2XL g4154(.A (n_106), .B (n_81), .Y (n_107));
  AOI21XL g4159(.A0 (n_102), .A1 (n_64), .B0 (n_43), .Y (n_103));
  AOI31X1 g4160(.A0 (n_176), .A1 (n_102), .A2 (n_100), .B0 (n_82), .Y
       (n_101));
  OAI21X1 g4162(.A0 (n_93), .A1 (n_59), .B0 (n_96), .Y (n_97));
  NAND4XL g4150(.A (n_92), .B (n_176), .C (n_100), .D (n_91), .Y
       (n_95));
  AOI21X1 g4144(.A0 (n_92), .A1 (n_91), .B0 (n_102), .Y (n_120));
  SDFFQXL \Sum_reg[2] (.CK (clk), .D (n_54), .SI (n_92), .SE (n_84), .Q
       (Sum[2]));
  INVXL g4173(.A (n_89), .Y (n_90));
  NAND2XL g4175(.A (n_80), .B (n_72), .Y (n_88));
  NOR2BX1 g4149(.AN (n_55), .B (n_91), .Y (n_112));
  INVXL g4164(.A (n_86), .Y (n_87));
  NOR3X1 g4157(.A (n_48), .B (n_84), .C (n_98), .Y (n_85));
  OAI2BB1X1 g4165(.A0N (n_96), .A1N (n_76), .B0 (n_22), .Y (n_82));
  OAI2BB1X1 g4166(.A0N (n_93), .A1N (n_80), .B0 (n_79), .Y (n_81));
  NAND2XL g4174(.A (n_80), .B (n_52), .Y (n_78));
  NOR3X1 g4177(.A (n_74), .B (n_65), .C (n_108), .Y (n_75));
  INVXL g4189(.A (n_72), .Y (n_73));
  INVXL g4179(.A (n_178), .Y (n_71));
  NAND2XL g4178(.A (n_80), .B (n_53), .Y (n_89));
  SDFFQXL \Sum_reg[0] (.CK (clk), .D (n_37), .SI (n_32), .SE (Cin_ff),
       .Q (Sum[0]));
  DFFQXL Cout_reg(.CK (clk), .D (n_51), .Q (Cout));
  SDFFQXL \Sum_reg[15] (.CK (clk), .D (n_174), .SI (n_34), .SE (C[14]),
       .Q (Sum[15]));
  SDFFQXL \Sum_reg[1] (.CK (clk), .D (n_67), .SI (n_30), .SE (Cin_ff),
       .Q (Sum[1]));
  NOR2XL g4196(.A (n_69), .B (n_68), .Y (n_72));
  NOR2BX2 g4156(.AN (n_67), .B (n_84), .Y (n_91));
  NAND2BXL g4191(.AN (n_65), .B (n_60), .Y (n_66));
  NOR2XL g4172(.A (n_65), .B (n_42), .Y (n_64));
  OR2XL g4180(.A (n_65), .B (n_98), .Y (n_63));
  NOR2XL g4185(.A (n_61), .B (n_60), .Y (n_62));
  INVXL g4188(.A (n_58), .Y (n_59));
  OAI21X1 g4167(.A0 (n_79), .A1 (n_57), .B0 (n_44), .Y (n_86));
  NAND3X1 g4194(.A (n_21), .B (n_61), .C (n_56), .Y (n_58));
  CLKINVX1 g4205(.A (n_68), .Y (n_100));
  OAI21X2 g4198(.A0 (n_55), .A1 (n_54), .B0 (n_47), .Y (n_102));
  NOR2BX1 g4182(.AN (n_104), .B (n_57), .Y (n_53));
  SDFFQXL \Sum_reg[13] (.CK (clk), .D (n_24), .SI (n_25), .SE (C[12]),
       .Q (Sum[13]));
  SDFFQXL \Sum_reg[14] (.CK (clk), .D (n_26), .SI (n_27), .SE (C[13]),
       .Q (Sum[14]));
  NOR2XL g4183(.A (n_69), .B (n_57), .Y (n_52));
  AO22X1 g4193(.A0 (C[15]), .A1 (n_174), .B0 (B_ff[15]), .B1
       (A_ff[15]), .Y (n_51));
  NAND2XL g4200(.A (n_56), .B (n_67), .Y (n_48));
  NOR2XL g4202(.A (n_47), .B (n_46), .Y (n_60));
  NOR2XL g4195(.A (n_45), .B (n_33), .Y (n_76));
  CLKINVX1 g4199(.A (n_80), .Y (n_108));
  AOI22X1 g4192(.A0 (n_43), .A1 (n_35), .B0 (A_ff[9]), .B1 (B_ff[9]),
       .Y (n_44));
  NAND4XL g4190(.A (n_106), .B (n_96), .C (n_41), .D (n_40), .Y (n_42));
  OAI21X2 g4187(.A0 (n_39), .A1 (n_69), .B0 (n_38), .Y (n_93));
  AOI21X2 g4168(.A0 (Cin_ff), .A1 (n_37), .B0 (n_18), .Y (n_84));
  NAND2X1 g4211(.A (n_56), .B (n_40), .Y (n_68));
  NAND2X2 g4209(.A (n_36), .B (n_56), .Y (n_65));
  AOI21X1 g4197(.A0 (A_ff[7]), .A1 (B_ff[7]), .B0 (n_179), .Y (n_79));
  NAND2X1 g4203(.A (n_106), .B (n_35), .Y (n_57));
  NAND2X1 g4210(.A (n_92), .B (n_40), .Y (n_98));
  CLKAND2X2 g4204(.A (n_96), .B (n_41), .Y (n_80));
  INVXL g4212(.A (n_174), .Y (n_34));
  NAND2XL g4206(.A (n_20), .B (n_61), .Y (n_33));
  INVXL g4214(.A (n_37), .Y (n_32));
  CLKINVX1 g4213(.A (n_35), .Y (n_31));
  CLKINVX1 g4219(.A (n_40), .Y (n_46));
  INVXL g4215(.A (n_67), .Y (n_30));
  CLKINVX1 g4220(.A (n_92), .Y (n_54));
  CLKINVX1 g4217(.A (n_106), .Y (n_74));
  CLKINVX2 g4223(.A (n_69), .Y (n_36));
  CLKINVX2 g4218(.A (n_45), .Y (n_56));
  INVXL g4222(.A (n_26), .Y (n_27));
  INVXL g4221(.A (n_24), .Y (n_25));
  OAI22X2 g4227(.A0 (B_ff[0]), .A1 (n_17), .B0 (A_ff[0]), .B1 (n_16),
       .Y (n_37));
  NOR2X4 g4229(.A (n_21), .B (n_20), .Y (n_69));
  CLKMX2X3 g4230(.A (A_ff[6]), .B (n_3), .S0 (B_ff[6]), .Y (n_96));
  OAI22X2 g4235(.A0 (B_ff[9]), .A1 (n_0), .B0 (A_ff[9]), .B1 (n_5), .Y
       (n_35));
  AOI22X2 g4231(.A0 (A_ff[4]), .A1 (n_7), .B0 (B_ff[4]), .B1 (n_4), .Y
       (n_45));
  MXI2X1 g4236(.A (n_8), .B (A_ff[1]), .S0 (B_ff[1]), .Y (n_67));
  OAI22X2 g4237(.A0 (B_ff[3]), .A1 (n_12), .B0 (A_ff[3]), .B1 (n_13),
       .Y (n_40));
  OAI22X2 g4238(.A0 (B_ff[2]), .A1 (n_2), .B0 (A_ff[2]), .B1 (n_9), .Y
       (n_92));
  OAI22X2 g4239(.A0 (B_ff[8]), .A1 (n_15), .B0 (A_ff[8]), .B1 (n_14),
       .Y (n_106));
  XNOR2X1 g4232(.A (A_ff[11]), .B (B_ff[11]), .Y (n_19));
  CLKXOR2X1 g4224(.A (A_ff[13]), .B (B_ff[13]), .Y (n_24));
  CLKXOR2X1 g4225(.A (A_ff[14]), .B (B_ff[14]), .Y (n_26));
  CLKXOR2X1 g4228(.A (A_ff[7]), .B (B_ff[7]), .Y (n_41));
  NOR2XL g4248(.A (n_17), .B (n_16), .Y (n_18));
  NOR2XL g4251(.A (n_15), .B (n_14), .Y (n_43));
  CLKXOR2X1 g4234(.A (A_ff[10]), .B (B_ff[10]), .Y (n_104));
  NOR2X2 g4247(.A (n_13), .B (n_12), .Y (n_61));
  NAND2XL g4242(.A (A_ff[2]), .B (B_ff[2]), .Y (n_47));
  NOR2BX2 g4241(.AN (B_ff[5]), .B (A_ff[5]), .Y (n_20));
  NAND2XL g4243(.A (A_ff[5]), .B (B_ff[5]), .Y (n_38));
  NAND2XL g4245(.A (A_ff[6]), .B (B_ff[6]), .Y (n_22));
  NOR2BX2 g4244(.AN (A_ff[5]), .B (B_ff[5]), .Y (n_21));
  NAND2XL g4246(.A (A_ff[4]), .B (B_ff[4]), .Y (n_39));
  NAND2XL g4250(.A (A_ff[1]), .B (B_ff[1]), .Y (n_55));
  CLKINVX1 g4277(.A (B_ff[2]), .Y (n_9));
  CLKINVX1 g4279(.A (A_ff[1]), .Y (n_8));
  CLKINVX2 g4278(.A (B_ff[4]), .Y (n_7));
  CLKINVX1 g4258(.A (B_ff[9]), .Y (n_5));
  CLKINVX1 g4281(.A (B_ff[8]), .Y (n_14));
  CLKINVX1 g4254(.A (B_ff[3]), .Y (n_13));
  CLKINVX1 g4282(.A (B_ff[0]), .Y (n_16));
  CLKINVX1 g4253(.A (A_ff[4]), .Y (n_4));
  CLKINVX1 g4256(.A (A_ff[6]), .Y (n_3));
  CLKINVX1 g4275(.A (A_ff[2]), .Y (n_2));
  CLKINVX1 g4255(.A (A_ff[9]), .Y (n_0));
  CLKINVX1 g4280(.A (A_ff[3]), .Y (n_12));
  CLKINVX1 g4276(.A (A_ff[8]), .Y (n_15));
  CLKINVX1 g4283(.A (A_ff[0]), .Y (n_17));
  DFFQX1 \B_ff_reg[14] (.CK (clk), .D (B[14]), .Q (B_ff[14]));
  DFFQX1 \B_ff_reg[11] (.CK (clk), .D (B[11]), .Q (B_ff[11]));
  DFFQXL \A_ff_reg[14] (.CK (clk), .D (A[14]), .Q (A_ff[14]));
  DFFQX2 \A_ff_reg[0] (.CK (clk), .D (A[0]), .Q (A_ff[0]));
  DFFQX1 \A_ff_reg[12] (.CK (clk), .D (A[12]), .Q (A_ff[12]));
  DFFQX1 \B_ff_reg[8] (.CK (clk), .D (B[8]), .Q (B_ff[8]));
  DFFQX1 \A_ff_reg[8] (.CK (clk), .D (A[8]), .Q (A_ff[8]));
  DFFQX1 \A_ff_reg[3] (.CK (clk), .D (A[3]), .Q (A_ff[3]));
  DFFQX1 \B_ff_reg[9] (.CK (clk), .D (B[9]), .Q (B_ff[9]));
  DFFQX1 \B_ff_reg[7] (.CK (clk), .D (B[7]), .Q (B_ff[7]));
  DFFQX2 \B_ff_reg[5] (.CK (clk), .D (B[5]), .Q (B_ff[5]));
  DFFQX2 \A_ff_reg[5] (.CK (clk), .D (A[5]), .Q (A_ff[5]));
  DFFQX1 \A_ff_reg[15] (.CK (clk), .D (A[15]), .Q (A_ff[15]));
  DFFQX1 \A_ff_reg[6] (.CK (clk), .D (A[6]), .Q (A_ff[6]));
  DFFQX2 \A_ff_reg[7] (.CK (clk), .D (A[7]), .Q (A_ff[7]));
  DFFQXL \A_ff_reg[11] (.CK (clk), .D (A[11]), .Q (A_ff[11]));
  DFFQX1 \B_ff_reg[13] (.CK (clk), .D (B[13]), .Q (B_ff[13]));
  DFFQX1 \B_ff_reg[12] (.CK (clk), .D (B[12]), .Q (B_ff[12]));
  DFFQXL \A_ff_reg[13] (.CK (clk), .D (A[13]), .Q (A_ff[13]));
  DFFQX1 \B_ff_reg[1] (.CK (clk), .D (B[1]), .Q (B_ff[1]));
  DFFQX1 \B_ff_reg[10] (.CK (clk), .D (B[10]), .Q (B_ff[10]));
  DFFQX1 \B_ff_reg[15] (.CK (clk), .D (B[15]), .Q (B_ff[15]));
  DFFQX2 \B_ff_reg[0] (.CK (clk), .D (B[0]), .Q (B_ff[0]));
  DFFQX2 \B_ff_reg[6] (.CK (clk), .D (B[6]), .Q (B_ff[6]));
  DFFQX1 \A_ff_reg[10] (.CK (clk), .D (A[10]), .Q (A_ff[10]));
  DFFQX2 \B_ff_reg[3] (.CK (clk), .D (B[3]), .Q (B_ff[3]));
  DFFQX2 \A_ff_reg[2] (.CK (clk), .D (A[2]), .Q (A_ff[2]));
  DFFQX1 Cin_ff_reg(.CK (clk), .D (Cin), .Q (Cin_ff));
  DFFQX2 \B_ff_reg[2] (.CK (clk), .D (B[2]), .Q (B_ff[2]));
  DFFQX1 \A_ff_reg[1] (.CK (clk), .D (A[1]), .Q (A_ff[1]));
  DFFQX2 \A_ff_reg[4] (.CK (clk), .D (A[4]), .Q (A_ff[4]));
  DFFQX2 \B_ff_reg[4] (.CK (clk), .D (B[4]), .Q (B_ff[4]));
  DFFQX1 \A_ff_reg[9] (.CK (clk), .D (A[9]), .Q (A_ff[9]));
  XOR2XL g2(.A (n_124), .B (n_96), .Y (n_172));
  CLKXOR2X1 g4351(.A (A_ff[12]), .B (B_ff[12]), .Y (n_173));
  CLKXOR2X1 g4352(.A (A_ff[15]), .B (B_ff[15]), .Y (n_174));
  NOR2BXL g4353(.AN (n_91), .B (n_98), .Y (n_175));
  NOR2BX1 g4354(.AN (n_96), .B (n_69), .Y (n_176));
  AO22XL g4355(.A0 (n_104), .A1 (n_86), .B0 (A_ff[10]), .B1 (B_ff[10]),
       .Y (n_177));
  OAI2BB1X1 g4356(.A0N (n_61), .A1N (n_56), .B0 (n_39), .Y (n_178));
  AOI2BB1XL g4357(.A0N (A_ff[7]), .A1N (B_ff[7]), .B0 (n_22), .Y
       (n_179));
  NOR3BX2 g4358(.AN (n_58), .B (n_93), .C (n_76), .Y (n_180));
endmodule

