
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Dec 12 2024 17:55:17 IST (Dec 12 2024 12:25:17 UTC)

// Verification Directory fv/CarryLookAheadAdder 

module CarryLookAheadAdder(A, B, Cin, clk, reset, Sum, Cout);
  input [3:0] A, B;
  input Cin, clk, reset;
  output [3:0] Sum;
  output Cout;
  wire [3:0] A, B;
  wire Cin, clk, reset;
  wire [3:0] Sum;
  wire Cout;
  wire [3:0] A_reg;
  wire [3:0] B_reg;
  wire Cin_reg, n_2, n_3, n_4, n_6, n_7, n_8, n_9;
  wire n_10, n_11, n_12, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_23, n_24, n_36, n_37;
  DFFRHQX1 Cout_reg(.RN (n_24), .CK (clk), .D (n_23), .Q (Cout));
  DFFRHQX8 \Sum_reg[3] (.RN (n_24), .CK (clk), .D (n_22), .Q (Sum[3]));
  OAI21X1 g2403(.A0 (n_20), .A1 (n_21), .B0 (n_2), .Y (n_23));
  MXI2X1 g2404(.A (n_19), .B (n_21), .S0 (n_20), .Y (n_22));
  SDFFRHQX1 \Sum_reg[2] (.RN (n_24), .CK (clk), .D (n_17), .SI (n_18),
       .SE (n_14), .Q (Sum[2]));
  CLKINVX2 g2406(.A (n_19), .Y (n_21));
  SDFFRHQX1 \Sum_reg[1] (.RN (n_24), .CK (clk), .D (n_15), .SI (n_16),
       .SE (n_37), .Q (Sum[1]));
  OAI21X2 g2407(.A0 (n_36), .A1 (n_18), .B0 (n_4), .Y (n_19));
  SDFFRHQX1 \Sum_reg[0] (.RN (n_24), .CK (clk), .D (n_7), .SI (n_6),
       .SE (Cin_reg), .Q (Sum[0]));
  INVXL g2409(.A (n_18), .Y (n_17));
  NOR2X2 g2410(.A (n_12), .B (n_10), .Y (n_18));
  INVXL g2415(.A (n_15), .Y (n_16));
  CLKINVX1 g2414(.A (n_36), .Y (n_14));
  NAND2XL g2416(.A (n_11), .B (n_8), .Y (n_15));
  OAI21X2 g2412(.A0 (n_9), .A1 (n_11), .B0 (n_3), .Y (n_12));
  NOR2X1 g2413(.A (n_9), .B (n_8), .Y (n_10));
  CLKINVX1 g2419(.A (n_6), .Y (n_7));
  XNOR2X1 g2422(.A (A_reg[3]), .B (B_reg[3]), .Y (n_20));
  OAI21X1 g2417(.A0 (B_reg[0]), .A1 (Cin_reg), .B0 (A_reg[0]), .Y
       (n_8));
  XNOR2X1 g2420(.A (A_reg[0]), .B (B_reg[0]), .Y (n_6));
  NAND2XL g2425(.A (A_reg[2]), .B (B_reg[2]), .Y (n_4));
  NOR2X2 g2423(.A (A_reg[1]), .B (B_reg[1]), .Y (n_9));
  NAND2X1 g2426(.A (A_reg[1]), .B (B_reg[1]), .Y (n_3));
  NAND2XL g2427(.A (A_reg[3]), .B (B_reg[3]), .Y (n_2));
  NAND2X1 g2424(.A (B_reg[0]), .B (Cin_reg), .Y (n_11));
  DFFRHQX1 \A_reg_reg[0] (.RN (n_24), .CK (clk), .D (A[0]), .Q
       (A_reg[0]));
  DFFRHQX4 Cin_reg_reg(.RN (n_24), .CK (clk), .D (Cin), .Q (Cin_reg));
  DFFRHQX1 \B_reg_reg[1] (.RN (n_24), .CK (clk), .D (B[1]), .Q
       (B_reg[1]));
  DFFRHQX1 \B_reg_reg[3] (.RN (n_24), .CK (clk), .D (B[3]), .Q
       (B_reg[3]));
  DFFRHQX1 \A_reg_reg[3] (.RN (n_24), .CK (clk), .D (A[3]), .Q
       (A_reg[3]));
  DFFRHQX1 \B_reg_reg[2] (.RN (n_24), .CK (clk), .D (B[2]), .Q
       (B_reg[2]));
  DFFRHQX4 \B_reg_reg[0] (.RN (n_24), .CK (clk), .D (B[0]), .Q
       (B_reg[0]));
  DFFRHQX1 \A_reg_reg[2] (.RN (n_24), .CK (clk), .D (A[2]), .Q
       (A_reg[2]));
  INVXL g2439(.A (reset), .Y (n_24));
  XNOR2X1 g2(.A (A_reg[2]), .B (B_reg[2]), .Y (n_36));
  CLKXOR2X1 g2454(.A (A_reg[1]), .B (B_reg[1]), .Y (n_37));
  DFFRHQX2 \A_reg_reg[1] (.RN (n_24), .CK (clk), .D (A[1]), .Q
       (A_reg[1]));
endmodule

