
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Dec 12 2024 17:59:55 IST (Dec 12 2024 12:29:55 UTC)

// Verification Directory fv/CarryLookAheadAdder 

module CarryLookAheadAdder(A, B, Cin, clk, reset, Sum, Cout);
  input [7:0] A, B;
  input Cin, clk, reset;
  output [7:0] Sum;
  output Cout;
  wire [7:0] A, B;
  wire Cin, clk, reset;
  wire [7:0] Sum;
  wire Cout;
  wire [7:0] B_reg;
  wire [7:0] A_reg;
  wire Cin_reg, UNCONNECTED, UNCONNECTED0, n_0, n_1, n_3, n_4, n_5;
  wire n_6, n_8, n_9, n_10, n_11, n_12, n_13, n_14;
  wire n_16, n_17, n_18, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_30, n_31, n_32, n_34;
  wire n_35, n_36, n_37, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_53, n_54, n_56, n_57, n_58, n_59, n_60, n_61;
  wire n_62, n_63, n_64, n_65, n_67, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_79, n_80;
  wire n_81, n_82, n_83, n_84, n_85, n_86, n_87, n_88;
  wire n_89, n_90, n_91, n_92, n_93, n_94, n_95, n_96;
  wire n_98, n_99, n_100, n_101, n_102, n_103, n_104, n_105;
  wire n_106, n_107, n_108, n_109, n_110, n_111, n_131, n_132;
  wire n_133, n_134, n_135, n_136, n_138;
  DFFRHQX8 \Sum_reg[6] (.RN (n_111), .CK (clk), .D (n_110), .Q
       (Sum[6]));
  DFFRHQX1 \Sum_reg[7] (.RN (n_111), .CK (clk), .D (n_109), .Q
       (Sum[7]));
  NAND3XL g16926(.A (n_101), .B (n_104), .C (n_108), .Y (n_110));
  SDFFRHQX1 \Sum_reg[5] (.RN (n_111), .CK (clk), .D (n_102), .SI
       (n_103), .SE (n_41), .Q (Sum[5]));
  OAI21X1 g16919(.A0 (n_69), .A1 (n_106), .B0 (n_107), .Y (n_109));
  DFFRHQX1 Cout_reg(.RN (n_111), .CK (clk), .D (n_105), .Q (Cout));
  NAND3XL g16927(.A (n_90), .B (n_96), .C (n_131), .Y (n_108));
  NAND2XL g16924(.A (n_99), .B (n_106), .Y (n_107));
  OAI211X1 g16928(.A0 (n_79), .A1 (n_81), .B0 (n_10), .C0 (n_94), .Y
       (n_105));
  SDFFRHQX1 \Sum_reg[3] (.RN (n_111), .CK (clk), .D (n_92), .SI (n_93),
       .SE (n_58), .Q (Sum[3]));
  NAND2X1 g16930(.A (n_100), .B (n_98), .Y (n_104));
  CLKINVX1 g16933(.A (n_102), .Y (n_103));
  AOI221X1 g16934(.A0 (n_100), .A1 (n_60), .B0 (n_100), .B1 (n_95), .C0
       (n_74), .Y (n_101));
  NOR2X1 g16936(.A (n_91), .B (n_85), .Y (n_102));
  OAI21X1 g16929(.A0 (n_76), .A1 (n_82), .B0 (n_80), .Y (n_99));
  INVXL g16941(.A (n_131), .Y (n_98));
  NOR2XL g16950(.A (n_45), .B (n_95), .Y (n_96));
  NAND3X1 g16935(.A (n_67), .B (n_50), .C (n_87), .Y (n_94));
  CLKINVX1 g16918(.A (n_92), .Y (n_93));
  NAND2XL g16939(.A (n_90), .B (n_77), .Y (n_91));
  SDFFRHQX1 \Sum_reg[2] (.RN (n_111), .CK (clk), .D (n_84), .SI (n_51),
       .SE (n_83), .Q (Sum[2]));
  NAND2X1 g16932(.A (n_88), .B (n_87), .Y (n_106));
  CLKINVX1 g16938(.A (n_87), .Y (n_86));
  AOI21X1 g16942(.A0 (n_70), .A1 (n_61), .B0 (n_43), .Y (n_85));
  OAI21X1 g16920(.A0 (n_84), .A1 (n_83), .B0 (n_32), .Y (n_92));
  NAND2XL g16946(.A (n_133), .B (n_132), .Y (n_82));
  AOI21X1 g16944(.A0 (n_36), .A1 (n_57), .B0 (n_75), .Y (n_81));
  AOI31X1 g16952(.A0 (n_79), .A1 (n_36), .A2 (n_56), .B0 (n_72), .Y
       (n_80));
  CLKINVX1 g16963(.A (n_77), .Y (n_95));
  NOR3X1 g16959(.A (n_75), .B (n_138), .C (n_73), .Y (n_76));
  OAI21X2 g16940(.A0 (n_39), .A1 (n_40), .B0 (n_59), .Y (n_87));
  NOR4X1 g16966(.A (n_64), .B (n_65), .C (n_134), .D (n_73), .Y (n_74));
  SDFFRHQX1 \Sum_reg[1] (.RN (n_111), .CK (clk), .D (n_53), .SI (n_35),
       .SE (n_54), .Q (Sum[1]));
  NAND2X1 g16968(.A (n_48), .B (n_47), .Y (n_77));
  NOR3X1 g16957(.A (n_75), .B (n_79), .C (n_36), .Y (n_72));
  CLKINVX1 g16962(.A (n_70), .Y (n_71));
  MXI2XL g16965(.A (n_138), .B (n_79), .S0 (n_67), .Y (n_69));
  CLKINVX1 g16951(.A (n_61), .Y (n_62));
  INVXL g16945(.A (n_90), .Y (n_60));
  SDFFRHQX1 \Sum_reg[0] (.RN (n_111), .CK (clk), .D (n_135), .SI
       (n_28), .SE (Cin_reg), .Q (Sum[0]));
  AOI21X1 g16954(.A0 (n_58), .A1 (n_136), .B0 (n_42), .Y (n_59));
  NAND2BX1 g16958(.AN (n_56), .B (n_44), .Y (n_57));
  AOI21X1 g16937(.A0 (n_54), .A1 (n_53), .B0 (n_46), .Y (n_83));
  NAND3X2 g16955(.A (n_26), .B (n_135), .C (n_88), .Y (n_61));
  NAND3BX2 g16967(.AN (n_27), .B (n_51), .C (n_88), .Y (n_70));
  NOR2XL g16976(.A (n_49), .B (n_79), .Y (n_50));
  NOR2X1 g16974(.A (n_84), .B (n_49), .Y (n_48));
  NOR2BX1 g16969(.AN (n_46), .B (n_34), .Y (n_47));
  NAND2XL g16984(.A (n_44), .B (n_36), .Y (n_45));
  CLKINVX1 g16973(.A (n_43), .Y (n_89));
  AOI21X1 g16947(.A0 (n_88), .A1 (n_42), .B0 (n_63), .Y (n_90));
  NOR2XL g16987(.A (n_41), .B (n_36), .Y (n_100));
  NAND2X1 g16975(.A (n_51), .B (n_54), .Y (n_40));
  NAND2XL g16949(.A (n_58), .B (n_53), .Y (n_39));
  NAND2XL g16977(.A (n_58), .B (n_54), .Y (n_43));
  NOR2XL g16985(.A (n_44), .B (n_37), .Y (n_73));
  INVXL g16956(.A (n_53), .Y (n_35));
  CLKINVX2 g16989(.A (n_37), .Y (n_36));
  CLKINVX1 g16981(.A (n_58), .Y (n_34));
  NOR2BX1 g16972(.AN (n_63), .B (n_41), .Y (n_56));
  CLKINVX2 g16979(.A (n_88), .Y (n_49));
  CLKINVX1 g16983(.A (n_138), .Y (n_79));
  OAI21X1 g16960(.A0 (n_12), .A1 (n_32), .B0 (n_9), .Y (n_42));
  NAND2X1 g16994(.A (n_31), .B (n_30), .Y (n_37));
  OAI21X2 g16993(.A0 (B_reg[3]), .A1 (n_22), .B0 (n_23), .Y (n_58));
  OAI21X2 g16995(.A0 (B_reg[4]), .A1 (n_20), .B0 (n_21), .Y (n_88));
  INVXL g16982(.A (n_135), .Y (n_28));
  OAI21X1 g16988(.A0 (n_8), .A1 (n_17), .B0 (n_31), .Y (n_67));
  CLKINVX2 g16980(.A (n_84), .Y (n_51));
  OAI21X2 g16961(.A0 (n_25), .A1 (n_11), .B0 (n_27), .Y (n_53));
  AOI22X1 g16992(.A0 (A_reg[5]), .A1 (n_14), .B0 (B_reg[5]), .B1
       (n_13), .Y (n_41));
  NOR2X1 g16971(.A (n_25), .B (n_24), .Y (n_26));
  AOI22X2 g16998(.A0 (A_reg[2]), .A1 (n_0), .B0 (B_reg[2]), .B1 (n_5),
       .Y (n_84));
  OAI22X2 g16997(.A0 (B_reg[1]), .A1 (n_6), .B0 (A_reg[1]), .B1 (n_3),
       .Y (n_54));
  NAND2X1 g17004(.A (B_reg[3]), .B (n_22), .Y (n_23));
  NAND2X2 g17003(.A (B_reg[4]), .B (n_20), .Y (n_21));
  NAND2X1 g17005(.A (B_reg[7]), .B (n_1), .Y (n_18));
  CLKINVX1 g17000(.A (n_17), .Y (n_30));
  CLKINVX1 g17011(.A (n_44), .Y (n_16));
  NOR2XL g17018(.A (A_reg[5]), .B (n_14), .Y (n_64));
  NOR2XL g17015(.A (B_reg[5]), .B (n_13), .Y (n_65));
  CLKINVX1 g17001(.A (n_31), .Y (n_75));
  NOR2XL g17002(.A (A_reg[3]), .B (B_reg[3]), .Y (n_12));
  NOR2XL g17006(.A (A_reg[0]), .B (B_reg[0]), .Y (n_11));
  NOR2X1 g17009(.A (A_reg[6]), .B (B_reg[6]), .Y (n_17));
  NOR2XL g17008(.A (A_reg[2]), .B (B_reg[2]), .Y (n_24));
  NAND2X1 g17010(.A (A_reg[6]), .B (B_reg[6]), .Y (n_31));
  AND2X1 g17021(.A (B_reg[4]), .B (A_reg[4]), .Y (n_63));
  NAND2XL g17013(.A (A_reg[7]), .B (B_reg[7]), .Y (n_10));
  NAND2XL g17014(.A (A_reg[3]), .B (B_reg[3]), .Y (n_9));
  NOR2XL g17012(.A (B_reg[5]), .B (A_reg[5]), .Y (n_8));
  NAND2X1 g17017(.A (A_reg[2]), .B (B_reg[2]), .Y (n_32));
  NAND2X1 g17016(.A (B_reg[0]), .B (A_reg[0]), .Y (n_27));
  CLKAND2X2 g17019(.A (B_reg[1]), .B (A_reg[1]), .Y (n_46));
  NAND2X1 g17020(.A (B_reg[5]), .B (A_reg[5]), .Y (n_44));
  CLKINVX2 g17029(.A (A_reg[3]), .Y (n_22));
  CLKINVX3 g17022(.A (A_reg[4]), .Y (n_20));
  CLKINVX1 g17028(.A (B_reg[2]), .Y (n_0));
  DFFRHQX4 \A_reg_reg[4] (.RN (n_111), .CK (clk), .D (A[4]), .Q
       (A_reg[4]));
  DFFRHQX1 \B_reg_reg[0] (.RN (n_111), .CK (clk), .D (B[0]), .Q
       (B_reg[0]));
  DFFRHQX1 \A_reg_reg[0] (.RN (n_111), .CK (clk), .D (A[0]), .Q
       (A_reg[0]));
  DFFRHQX1 \B_reg_reg[6] (.RN (n_111), .CK (clk), .D (B[6]), .Q
       (B_reg[6]));
  DFFRHQX1 \A_reg_reg[6] (.RN (n_111), .CK (clk), .D (A[6]), .Q
       (A_reg[6]));
  DFFRHQX2 \A_reg_reg[3] (.RN (n_111), .CK (clk), .D (A[3]), .Q
       (A_reg[3]));
  DFFRHQX1 \B_reg_reg[3] (.RN (n_111), .CK (clk), .D (B[3]), .Q
       (B_reg[3]));
  INVXL g17052(.A (reset), .Y (n_111));
  OAI21X1 g2(.A0 (n_62), .A1 (n_71), .B0 (n_89), .Y (n_131));
  OAI211X1 g17079(.A0 (n_64), .A1 (n_65), .B0 (n_63), .C0 (n_138), .Y
       (n_132));
  OAI21X1 g17080(.A0 (n_75), .A1 (n_16), .B0 (n_138), .Y (n_133));
  AOI21X1 g17081(.A0 (n_30), .A1 (n_31), .B0 (A_reg[5]), .Y (n_134));
  CLKXOR2X1 g17082(.A (B_reg[0]), .B (A_reg[0]), .Y (n_135));
  DFFRX4 \B_reg_reg[2] (.RN (n_111), .CK (clk), .D (B[2]), .Q
       (B_reg[2]), .QN (UNCONNECTED));
  SDFFRXL \Sum_reg[4] (.RN (n_111), .CK (clk), .D (n_49), .SI (n_88),
       .SE (n_86), .Q (Sum[4]), .QN (UNCONNECTED0));
  DFFRX1 \A_reg_reg[1] (.RN (n_111), .CK (clk), .D (A[1]), .Q
       (A_reg[1]), .QN (n_6));
  DFFRX1 \A_reg_reg[2] (.RN (n_111), .CK (clk), .D (A[2]), .Q
       (A_reg[2]), .QN (n_5));
  DFFRX1 \B_reg_reg[7] (.RN (n_111), .CK (clk), .D (B[7]), .Q
       (B_reg[7]), .QN (n_4));
  DFFRX1 \B_reg_reg[1] (.RN (n_111), .CK (clk), .D (B[1]), .Q
       (B_reg[1]), .QN (n_3));
  DFFRX1 \A_reg_reg[7] (.RN (n_111), .CK (clk), .D (A[7]), .Q
       (A_reg[7]), .QN (n_1));
  DFFRX1 \B_reg_reg[5] (.RN (n_111), .CK (clk), .D (B[5]), .Q
       (B_reg[5]), .QN (n_14));
  DFFRX1 \A_reg_reg[5] (.RN (n_111), .CK (clk), .D (A[5]), .Q
       (A_reg[5]), .QN (n_13));
  DFFRX1 Cin_reg_reg(.RN (n_111), .CK (clk), .D (Cin), .Q (Cin_reg),
       .QN (n_25));
  NOR2BXL g17109(.AN (n_46), .B (n_24), .Y (n_136));
  DFFRHQX2 \B_reg_reg[4] (.RN (n_111), .CK (clk), .D (B[4]), .Q
       (B_reg[4]));
  OAI2BB1X2 g17113(.A0N (A_reg[7]), .A1N (n_4), .B0 (n_18), .Y (n_138));
endmodule

