
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Dec 13 2024 13:01:11 IST (Dec 13 2024 07:31:11 UTC)

// Verification Directory fv/prefix_adder_8bit 

module prefix_adder_8bit(clk, A, B, Cin, Sum, Cout);
  input clk, Cin;
  input [7:0] A, B;
  output [7:0] Sum;
  output Cout;
  wire clk, Cin;
  wire [7:0] A, B;
  wire [7:0] Sum;
  wire Cout;
  wire [7:0] B_ff;
  wire [7:0] A_ff;
  wire Cin_ff, n_0, n_1, n_2, n_4, n_5, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_18, n_19, n_20, n_21, n_22, n_23, n_24, n_26;
  wire n_27, n_28, n_29, n_30, n_31, n_32, n_33, n_34;
  wire n_35, n_36, n_37, n_39, n_40, n_41, n_42, n_43;
  wire n_44, n_45, n_46, n_47, n_48, n_49, n_50, n_51;
  wire n_53, n_54, n_55, n_56, n_57, n_58, n_59, n_60;
  wire n_61, n_63, n_64, n_65, n_66, n_68, n_69, n_70;
  wire n_71, n_72, n_73, n_74, n_75, n_76, n_77, n_78;
  wire n_79, n_80, n_81, n_82, n_101, n_102, n_103, n_104;
  DFFQXL \Sum_reg[7] (.CK (clk), .D (n_82), .Q (Sum[7]));
  DFFQXL Cout_reg(.CK (clk), .D (n_81), .Q (Cout));
  DFFHQX1 \Sum_reg[6] (.CK (clk), .D (n_80), .Q (Sum[6]));
  NAND4XL g10466(.A (n_65), .B (n_66), .C (n_74), .D (n_79), .Y (n_82));
  DFFHQX1 \Sum_reg[5] (.CK (clk), .D (n_76), .Q (Sum[5]));
  OAI2BB1X1 g10465(.A0N (B_ff[7]), .A1N (A_ff[7]), .B0 (n_78), .Y
       (n_81));
  OAI21X1 g10464(.A0 (n_27), .A1 (n_75), .B0 (n_72), .Y (n_80));
  AOI31X1 g10473(.A0 (n_77), .A1 (n_73), .A2 (n_50), .B0 (n_70), .Y
       (n_79));
  OAI21X1 g10470(.A0 (n_60), .A1 (n_69), .B0 (n_77), .Y (n_78));
  MXI2XL g10471(.A (n_103), .B (n_75), .S0 (n_46), .Y (n_76));
  NAND3X1 g10472(.A (n_73), .B (n_77), .C (n_71), .Y (n_74));
  AOI21X1 g10469(.A0 (n_104), .A1 (n_63), .B0 (n_49), .Y (n_72));
  SDFFQXL \Sum_reg[4] (.CK (clk), .D (n_61), .SI (n_71), .SE (n_47), .Q
       (Sum[4]));
  SDFFQXL \Sum_reg[3] (.CK (clk), .D (n_56), .SI (n_68), .SE (n_30), .Q
       (Sum[3]));
  NOR2X1 g10476(.A (n_73), .B (n_77), .Y (n_70));
  NOR3X1 g10480(.A (n_58), .B (n_68), .C (n_26), .Y (n_69));
  CLKINVX1 g10474(.A (n_103), .Y (n_75));
  NAND2XL g10487(.A (n_54), .B (n_64), .Y (n_66));
  AOI21X1 g10490(.A0 (n_32), .A1 (n_45), .B0 (n_31), .Y (n_73));
  NAND2XL g10478(.A (n_57), .B (n_64), .Y (n_65));
  NOR3X1 g10479(.A (n_48), .B (n_59), .C (n_51), .Y (n_63));
  INVXL g10481(.A (n_71), .Y (n_61));
  OAI32X1 g10488(.A0 (n_59), .A1 (n_37), .A2 (n_58), .B0 (n_9), .B1
       (n_33), .Y (n_60));
  NOR2XL g10483(.A (n_77), .B (n_55), .Y (n_57));
  CLKINVX1 g10482(.A (n_56), .Y (n_68));
  NOR2BX1 g10484(.AN (n_55), .B (n_53), .Y (n_71));
  NOR2BX1 g10494(.AN (n_53), .B (n_77), .Y (n_54));
  CLKINVX1 g10497(.A (n_64), .Y (n_50));
  OAI32X1 g10503(.A0 (n_48), .A1 (n_47), .A2 (n_59), .B0 (n_44), .B1
       (n_102), .Y (n_49));
  NAND2XL g10485(.A (n_41), .B (n_43), .Y (n_56));
  NOR3X1 g10501(.A (n_40), .B (n_46), .C (n_23), .Y (n_64));
  DFFQXL \Sum_reg[0] (.CK (clk), .D (n_29), .Q (Sum[0]));
  SDFFQXL \Sum_reg[2] (.CK (clk), .D (n_34), .SI (n_39), .SE (n_35), .Q
       (Sum[2]));
  OAI21X2 g10498(.A0 (n_10), .A1 (n_22), .B0 (n_44), .Y (n_45));
  NOR2XL g10489(.A (n_43), .B (n_24), .Y (n_51));
  NOR3X1 g10500(.A (n_41), .B (n_40), .C (n_39), .Y (n_42));
  SDFFQXL \Sum_reg[1] (.CK (clk), .D (Cin_ff), .SI (n_28), .SE (n_36),
       .Q (Sum[1]));
  OAI21X1 g10506(.A0 (n_41), .A1 (n_39), .B0 (n_15), .Y (n_53));
  NAND3XL g10496(.A (n_36), .B (n_35), .C (n_34), .Y (n_55));
  AOI221X1 g10504(.A0 (A_ff[6]), .A1 (B_ff[6]), .B0 (n_32), .B1 (n_48),
       .C0 (n_31), .Y (n_33));
  NAND2XL g10508(.A (n_32), .B (n_47), .Y (n_58));
  AOI21X1 g10505(.A0 (n_16), .A1 (n_30), .B0 (n_11), .Y (n_37));
  MXI2XL g10510(.A (n_28), .B (Cin_ff), .S0 (n_101), .Y (n_29));
  NAND2XL g10509(.A (n_47), .B (n_59), .Y (n_27));
  NAND3X1 g10499(.A (n_102), .B (n_30), .C (n_34), .Y (n_26));
  NAND2X1 g10493(.A (n_36), .B (n_35), .Y (n_43));
  NAND2XL g10507(.A (n_30), .B (n_34), .Y (n_24));
  CLKINVX1 g10518(.A (n_47), .Y (n_23));
  NOR2X1 g10519(.A (n_21), .B (n_19), .Y (n_22));
  CLKINVX1 g10516(.A (n_32), .Y (n_46));
  CLKINVX1 g10512(.A (n_34), .Y (n_39));
  CLKINVX1 g10511(.A (n_102), .Y (n_59));
  CLKINVX1 g10514(.A (n_30), .Y (n_40));
  OAI2BB1X2 g10517(.A0N (Cin_ff), .A1N (B_ff[0]), .B0 (n_12), .Y
       (n_35));
  NAND2X2 g10522(.A (n_18), .B (n_20), .Y (n_47));
  CLKINVX1 g10530(.A (n_20), .Y (n_21));
  CLKINVX2 g10529(.A (n_18), .Y (n_19));
  OAI22X2 g10521(.A0 (B_ff[2]), .A1 (n_1), .B0 (A_ff[2]), .B1 (n_2), .Y
       (n_34));
  MXI2X1 g10525(.A (n_0), .B (A_ff[1]), .S0 (B_ff[1]), .Y (n_36));
  OAI22X1 g10526(.A0 (B_ff[5]), .A1 (n_14), .B0 (A_ff[5]), .B1 (n_13),
       .Y (n_32));
  OAI22X2 g10527(.A0 (B_ff[3]), .A1 (n_5), .B0 (A_ff[3]), .B1 (n_8), .Y
       (n_30));
  CLKINVX1 g10513(.A (n_15), .Y (n_16));
  NAND2X2 g10534(.A (B_ff[4]), .B (n_4), .Y (n_20));
  NAND2X2 g10533(.A (A_ff[4]), .B (n_7), .Y (n_18));
  NOR2XL g10537(.A (n_14), .B (n_13), .Y (n_31));
  OAI21X1 g10520(.A0 (B_ff[0]), .A1 (Cin_ff), .B0 (A_ff[0]), .Y (n_12));
  CLKINVX1 g10515(.A (n_10), .Y (n_11));
  CLKINVX1 g10531(.A (n_44), .Y (n_48));
  CLKXOR2X1 g10523(.A (A_ff[7]), .B (B_ff[7]), .Y (n_77));
  NOR2XL g10532(.A (A_ff[6]), .B (B_ff[6]), .Y (n_9));
  NAND2XL g10536(.A (A_ff[3]), .B (B_ff[3]), .Y (n_10));
  NAND2XL g10538(.A (A_ff[2]), .B (B_ff[2]), .Y (n_15));
  NAND2X1 g10535(.A (A_ff[4]), .B (B_ff[4]), .Y (n_44));
  NAND2XL g10539(.A (A_ff[1]), .B (B_ff[1]), .Y (n_41));
  CLKINVX1 g10545(.A (B_ff[3]), .Y (n_8));
  CLKINVX2 g10542(.A (B_ff[4]), .Y (n_7));
  CLKINVX1 g10544(.A (A_ff[3]), .Y (n_5));
  CLKINVX3 g10541(.A (A_ff[4]), .Y (n_4));
  CLKINVX1 g10543(.A (A_ff[5]), .Y (n_14));
  CLKINVX1 g10557(.A (B_ff[2]), .Y (n_2));
  CLKINVX2 g10540(.A (A_ff[2]), .Y (n_1));
  CLKINVX1 g10554(.A (A_ff[1]), .Y (n_0));
  CLKINVX1 g10555(.A (B_ff[5]), .Y (n_13));
  CLKINVX1 g10559(.A (Cin_ff), .Y (n_28));
  DFFQX1 \A_ff_reg[5] (.CK (clk), .D (A[5]), .Q (A_ff[5]));
  DFFQX1 \B_ff_reg[5] (.CK (clk), .D (B[5]), .Q (B_ff[5]));
  DFFQX1 \B_ff_reg[7] (.CK (clk), .D (B[7]), .Q (B_ff[7]));
  DFFQX1 \A_ff_reg[0] (.CK (clk), .D (A[0]), .Q (A_ff[0]));
  DFFQX4 \A_ff_reg[4] (.CK (clk), .D (A[4]), .Q (A_ff[4]));
  DFFQX2 \B_ff_reg[3] (.CK (clk), .D (B[3]), .Q (B_ff[3]));
  DFFQX2 \B_ff_reg[0] (.CK (clk), .D (B[0]), .Q (B_ff[0]));
  DFFQX2 \A_ff_reg[2] (.CK (clk), .D (A[2]), .Q (A_ff[2]));
  DFFQX1 \B_ff_reg[1] (.CK (clk), .D (B[1]), .Q (B_ff[1]));
  DFFQX1 \A_ff_reg[7] (.CK (clk), .D (A[7]), .Q (A_ff[7]));
  DFFQX1 \B_ff_reg[6] (.CK (clk), .D (B[6]), .Q (B_ff[6]));
  DFFQX1 \A_ff_reg[1] (.CK (clk), .D (A[1]), .Q (A_ff[1]));
  DFFQX2 \B_ff_reg[2] (.CK (clk), .D (B[2]), .Q (B_ff[2]));
  DFFQX2 \A_ff_reg[3] (.CK (clk), .D (A[3]), .Q (A_ff[3]));
  DFFQX4 \B_ff_reg[4] (.CK (clk), .D (B[4]), .Q (B_ff[4]));
  DFFQX1 \A_ff_reg[6] (.CK (clk), .D (A[6]), .Q (A_ff[6]));
  DFFQX2 Cin_ff_reg(.CK (clk), .D (Cin), .Q (Cin_ff));
  CLKXOR2X1 g2(.A (A_ff[0]), .B (B_ff[0]), .Y (n_101));
  CLKXOR2X1 g10595(.A (A_ff[6]), .B (B_ff[6]), .Y (n_102));
  NAND2BX1 g10596(.AN (n_51), .B (n_104), .Y (n_103));
  NOR2BX1 g10597(.AN (n_37), .B (n_42), .Y (n_104));
endmodule

