
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Dec 13 2024 12:59:39 IST (Dec 13 2024 07:29:39 UTC)

// Verification Directory fv/prefix_adder_4bit 

module prefix_adder_4bit(clk, A, B, Cin, Sum, Cout);
  input clk, Cin;
  input [3:0] A, B;
  output [3:0] Sum;
  output Cout;
  wire clk, Cin;
  wire [3:0] A, B;
  wire [3:0] Sum;
  wire Cout;
  wire [3:0] A_ff;
  wire [3:0] B_ff;
  wire Cin_ff, n_0, n_2, n_3, n_4, n_5, n_7, n_9;
  wire n_10, n_12, n_13, n_14, n_15, n_16, n_17, n_18;
  wire n_19, n_20, n_21, n_22, n_33, n_34;
  DFFHQX1 Cout_reg(.CK (clk), .D (n_22), .Q (Cout));
  OAI221X1 g2820(.A0 (n_20), .A1 (n_21), .B0 (n_21), .B1 (n_10), .C0
       (n_17), .Y (n_22));
  SDFFQXL \Sum_reg[3] (.CK (clk), .D (n_19), .SI (n_18), .SE (n_16), .Q
       (Sum[3]));
  SDFFQXL \Sum_reg[2] (.CK (clk), .D (n_14), .SI (n_7), .SE (n_33), .Q
       (Sum[2]));
  NOR2XL g2829(.A (n_13), .B (n_34), .Y (n_20));
  CLKINVX1 g2823(.A (n_18), .Y (n_19));
  AOI32X1 g2830(.A0 (A_ff[2]), .A1 (B_ff[2]), .A2 (n_16), .B0
       (A_ff[3]), .B1 (B_ff[3]), .Y (n_17));
  SDFFQXL \Sum_reg[1] (.CK (clk), .D (Cin_ff), .SI (n_12), .SE (n_15),
       .Q (Sum[1]));
  AOI21X1 g2825(.A0 (n_15), .A1 (n_14), .B0 (n_13), .Y (n_18));
  SDFFQXL \Sum_reg[0] (.CK (clk), .D (Cin_ff), .SI (n_12), .SE (n_9),
       .Q (Sum[0]));
  NAND3X1 g2824(.A (Cin_ff), .B (n_9), .C (n_15), .Y (n_10));
  NAND2XL g2831(.A (n_33), .B (n_16), .Y (n_21));
  INVXL g2827(.A (n_14), .Y (n_7));
  OAI21X1 g2828(.A0 (n_12), .A1 (n_2), .B0 (n_5), .Y (n_14));
  OAI22X2 g2837(.A0 (B_ff[1]), .A1 (n_4), .B0 (A_ff[1]), .B1 (n_3), .Y
       (n_15));
  MXI2X1 g2835(.A (n_0), .B (A_ff[3]), .S0 (B_ff[3]), .Y (n_16));
  CLKXOR2X1 g2836(.A (A_ff[0]), .B (B_ff[0]), .Y (n_9));
  NOR2XL g2840(.A (n_4), .B (n_3), .Y (n_13));
  NOR2XL g2838(.A (A_ff[0]), .B (B_ff[0]), .Y (n_2));
  NAND2XL g2839(.A (A_ff[0]), .B (B_ff[0]), .Y (n_5));
  CLKINVX1 g2841(.A (A_ff[1]), .Y (n_4));
  INVXL g2843(.A (A_ff[3]), .Y (n_0));
  CLKINVX1 g2848(.A (B_ff[1]), .Y (n_3));
  CLKINVX1 g2849(.A (Cin_ff), .Y (n_12));
  DFFQX1 \A_ff_reg[1] (.CK (clk), .D (A[1]), .Q (A_ff[1]));
  DFFQX1 \B_ff_reg[3] (.CK (clk), .D (B[3]), .Q (B_ff[3]));
  DFFQX1 \A_ff_reg[2] (.CK (clk), .D (A[2]), .Q (A_ff[2]));
  DFFQX1 \A_ff_reg[3] (.CK (clk), .D (A[3]), .Q (A_ff[3]));
  DFFQX1 \B_ff_reg[2] (.CK (clk), .D (B[2]), .Q (B_ff[2]));
  DFFQX1 \B_ff_reg[1] (.CK (clk), .D (B[1]), .Q (B_ff[1]));
  DFFQX1 \B_ff_reg[0] (.CK (clk), .D (B[0]), .Q (B_ff[0]));
  DFFQX1 \A_ff_reg[0] (.CK (clk), .D (A[0]), .Q (A_ff[0]));
  DFFQX1 Cin_ff_reg(.CK (clk), .D (Cin), .Q (Cin_ff));
  CLKXOR2X1 g2(.A (A_ff[2]), .B (B_ff[2]), .Y (n_33));
  NOR2BXL g2869(.AN (n_15), .B (n_5), .Y (n_34));
endmodule

