
// Generated by Cadence Genus(TM) Synthesis Solution 20.11-s111_1
// Generated on: Dec 12 2024 18:04:17 IST (Dec 12 2024 12:34:17 UTC)

// Verification Directory fv/CarryLookAheadAdder 

module CarryLookAheadAdder(A, B, Cin, clk, reset, Sum, Cout);
  input [15:0] A, B;
  input Cin, clk, reset;
  output [15:0] Sum;
  output Cout;
  wire [15:0] A, B;
  wire Cin, clk, reset;
  wire [15:0] Sum;
  wire Cout;
  wire [15:0] A_reg;
  wire [15:0] B_reg;
  wire Cin_reg, n_1, n_2, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_11, n_12, n_13, n_14, n_15, n_16, n_17;
  wire n_18, n_19, n_20, n_22, n_23, n_24, n_25, n_26;
  wire n_27, n_29, n_30, n_31, n_32, n_33, n_34, n_35;
  wire n_38, n_39, n_40, n_41, n_42, n_43, n_45, n_46;
  wire n_47, n_49, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_90, n_92, n_93, n_94, n_95, n_96, n_97, n_98;
  wire n_99, n_100, n_101, n_102, n_103, n_104, n_105, n_106;
  wire n_107, n_108, n_109, n_111, n_112, n_113, n_114, n_115;
  wire n_116, n_117, n_118, n_119, n_120, n_121, n_122, n_123;
  wire n_124, n_125, n_127, n_128, n_129, n_130, n_131, n_132;
  wire n_133, n_134, n_135, n_136, n_137, n_138, n_139, n_140;
  wire n_141, n_142, n_143, n_144, n_145, n_146, n_147, n_148;
  wire n_149, n_150, n_151, n_152, n_153, n_154, n_155, n_156;
  wire n_157, n_158, n_159, n_160, n_161, n_162, n_163, n_164;
  wire n_165, n_166, n_167, n_168, n_169, n_170, n_171, n_172;
  wire n_173, n_174, n_176, n_177, n_178, n_180, n_181, n_182;
  wire n_183, n_184, n_185, n_186, n_187, n_188, n_189, n_190;
  wire n_191, n_192, n_193, n_194, n_195, n_196, n_197, n_198;
  wire n_199, n_200, n_201, n_202, n_203, n_204, n_205, n_206;
  wire n_207, n_208, n_209, n_210, n_211, n_212, n_213, n_214;
  wire n_215, n_216, n_217, n_218, n_219, n_220, n_221, n_222;
  wire n_223, n_224, n_225, n_227, n_228, n_230, n_231, n_232;
  wire n_233, n_234, n_237, n_238, n_239, n_275, n_276, n_277;
  wire n_278, n_279, n_280, n_281, n_282, n_283, n_284, n_285;
  DFFRHQX1 \Sum_reg[15] (.RN (n_239), .CK (clk), .D (n_237), .Q
       (Sum[15]));
  DFFRHQX1 \Sum_reg[12] (.RN (n_239), .CK (clk), .D (n_275), .Q
       (Sum[12]));
  DFFRHQX1 \Sum_reg[14] (.RN (n_239), .CK (clk), .D (n_238), .Q
       (Sum[14]));
  DFFRHQX1 \Sum_reg[13] (.RN (n_239), .CK (clk), .D (n_276), .Q
       (Sum[13]));
  DFFRHQX1 Cout_reg(.RN (n_239), .CK (clk), .D (n_234), .Q (Cout));
  DFFRHQX1 \Sum_reg[10] (.RN (n_239), .CK (clk), .D (n_231), .Q
       (Sum[10]));
  SDFFRHQX1 \Sum_reg[9] (.RN (n_239), .CK (clk), .D (n_223), .SI
       (n_124), .SE (n_164), .Q (Sum[9]));
  SDFFRHQX1 \Sum_reg[11] (.RN (n_239), .CK (clk), .D (n_217), .SI
       (n_201), .SE (n_215), .Q (Sum[11]));
  MXI2X1 g10138(.A (n_224), .B (n_222), .S0 (n_227), .Y (n_238));
  OAI21X1 g10129(.A0 (n_219), .A1 (n_233), .B0 (n_232), .Y (n_237));
  SDFFRHQX1 \Sum_reg[6] (.RN (n_239), .CK (clk), .D (n_230), .SI
       (n_206), .SE (n_56), .Q (Sum[6]));
  OAI21X1 g10128(.A0 (n_168), .A1 (n_233), .B0 (n_207), .Y (n_234));
  SDFFRHQX1 \Sum_reg[8] (.RN (n_239), .CK (clk), .D (n_192), .SI
       (n_156), .SE (n_208), .Q (Sum[8]));
  OAI211X1 g10137(.A0 (n_205), .A1 (n_190), .B0 (n_210), .C0 (n_209),
       .Y (n_232));
  OAI21X1 g10123(.A0 (n_200), .A1 (n_230), .B0 (n_213), .Y (n_231));
  SDFFRHQX1 \Sum_reg[7] (.RN (n_239), .CK (clk), .D (n_133), .SI
       (n_141), .SE (n_218), .Q (Sum[7]));
  AOI21X1 g10149(.A0 (n_194), .A1 (n_187), .B0 (n_148), .Y (n_227));
  MXI2XL g10170(.A (n_221), .B (n_220), .S0 (n_173), .Y (n_224));
  SDFFRHQX1 \Sum_reg[4] (.RN (n_239), .CK (clk), .D (n_161), .SI
       (n_157), .SE (n_162), .Q (Sum[4]));
  MXI2XL g10148(.A (n_135), .B (n_123), .S0 (n_165), .Y (n_223));
  MXI2XL g10167(.A (n_221), .B (n_220), .S0 (n_182), .Y (n_222));
  MXI2XL g10168(.A (n_184), .B (n_204), .S0 (n_169), .Y (n_219));
  AOI2BB1X1 g10145(.A0N (n_214), .A1N (n_218), .B0 (n_140), .Y (n_225));
  OAI21X1 g10146(.A0 (n_143), .A1 (n_218), .B0 (n_147), .Y (n_228));
  OAI21X1 g10160(.A0 (n_116), .A1 (n_199), .B0 (n_188), .Y (n_217));
  AOI31X1 g10175(.A0 (n_185), .A1 (n_107), .A2 (n_196), .B0 (n_198), .Y
       (n_216));
  OAI21X1 g10153(.A0 (n_214), .A1 (n_181), .B0 (n_64), .Y (n_215));
  NAND2XL g10127(.A (n_176), .B (n_230), .Y (n_213));
  MXI2XL g10182(.A (n_280), .B (n_197), .S0 (n_166), .Y (n_212));
  NOR2XL g10174(.A (n_202), .B (n_195), .Y (n_211));
  AND2X1 g10141(.A (n_210), .B (n_209), .Y (n_233));
  SDFFRHQX1 \Sum_reg[5] (.RN (n_239), .CK (clk), .D (n_193), .SI
       (n_208), .SE (n_146), .Q (Sum[5]));
  AOI21XL g10164(.A0 (n_128), .A1 (n_167), .B0 (n_186), .Y (n_207));
  CLKINVX1 g10130(.A (n_230), .Y (n_206));
  OAI221X1 g10173(.A0 (n_204), .A1 (n_183), .B0 (n_204), .B1 (n_189),
       .C0 (n_277), .Y (n_205));
  AOI211XL g10181(.A0 (n_159), .A1 (n_152), .B0 (n_202), .C0 (n_154),
       .Y (n_203));
  MXI2XL g10185(.A (n_139), .B (n_150), .S0 (n_149), .Y (n_201));
  SDFFRHQX1 \Sum_reg[3] (.RN (n_239), .CK (clk), .D (n_72), .SI
       (n_113), .SE (n_180), .Q (Sum[3]));
  MXI2XL g10161(.A (n_174), .B (n_285), .S0 (n_199), .Y (n_200));
  OAI31X1 g10197(.A0 (n_108), .A1 (n_197), .A2 (n_196), .B0 (n_111), .Y
       (n_198));
  AOI21XL g10195(.A0 (n_153), .A1 (n_158), .B0 (n_160), .Y (n_195));
  NAND3X1 g10144(.A (n_191), .B (n_194), .C (n_193), .Y (n_209));
  MXI2XL g10152(.A (n_155), .B (n_191), .S0 (n_194), .Y (n_192));
  NOR4BX1 g10184(.AN (n_189), .B (n_178), .C (n_177), .D (n_142), .Y
       (n_190));
  NOR2XL g10169(.A (n_117), .B (n_151), .Y (n_188));
  CLKINVX1 g10155(.A (n_218), .Y (n_187));
  NAND2X2 g10134(.A (n_52), .B (n_163), .Y (n_230));
  OAI221X1 g10186(.A0 (n_185), .A1 (n_138), .B0 (n_184), .B1 (n_183),
       .C0 (n_18), .Y (n_186));
  OAI211X1 g10190(.A0 (n_60), .A1 (n_172), .B0 (n_171), .C0 (n_170), .Y
       (n_182));
  AOI2BB1X1 g10165(.A0N (n_99), .A1N (n_180), .B0 (n_98), .Y (n_181));
  MXI2XL g10147(.A (n_285), .B (n_174), .S0 (n_136), .Y (n_176));
  OAI211X1 g10199(.A0 (n_93), .A1 (n_172), .B0 (n_171), .C0 (n_170), .Y
       (n_173));
  AND3X1 g10200(.A (n_189), .B (n_183), .C (n_130), .Y (n_169));
  NAND2XL g10202(.A (n_102), .B (n_167), .Y (n_168));
  AOI211X1 g10213(.A0 (n_127), .A1 (n_104), .B0 (n_109), .C0 (n_284),
       .Y (n_166));
  NAND2XL g10158(.A (n_120), .B (n_210), .Y (n_165));
  CLKINVX1 g10139(.A (n_163), .Y (n_164));
  NAND2X2 g10179(.A (n_162), .B (n_161), .Y (n_218));
  NOR2XL g10201(.A (n_159), .B (n_158), .Y (n_160));
  INVXL g10188(.A (n_161), .Y (n_157));
  MXI2XL g10187(.A (n_155), .B (n_191), .S0 (n_145), .Y (n_156));
  NOR2XL g10204(.A (n_153), .B (n_152), .Y (n_154));
  NOR3X1 g10172(.A (n_150), .B (n_285), .C (n_137), .Y (n_151));
  NAND2BX1 g10205(.AN (n_158), .B (n_97), .Y (n_149));
  NAND2XL g10157(.A (n_144), .B (n_147), .Y (n_148));
  NAND2X1 g10154(.A (n_146), .B (n_193), .Y (n_163));
  SDFFRHQX1 \Sum_reg[2] (.RN (n_239), .CK (clk), .D (n_129), .SI
       (n_90), .SE (n_43), .Q (Sum[2]));
  NAND2X2 g10193(.A (n_114), .B (n_115), .Y (n_161));
  NAND2X1 g10189(.A (n_191), .B (n_145), .Y (n_210));
  NAND2X1 g10166(.A (n_144), .B (n_143), .Y (n_194));
  NAND2XL g10203(.A (n_204), .B (n_183), .Y (n_142));
  MXI2XL g10180(.A (n_132), .B (n_131), .S0 (n_140), .Y (n_141));
  NOR2XL g10223(.A (n_139), .B (n_138), .Y (n_167));
  NAND2XL g10178(.A (n_134), .B (n_137), .Y (n_199));
  CLKINVX1 g10159(.A (n_193), .Y (n_208));
  OAI21X1 g10162(.A0 (n_135), .A1 (n_122), .B0 (n_134), .Y (n_136));
  MXI2XL g10198(.A (n_132), .B (n_131), .S0 (n_119), .Y (n_133));
  NOR2XL g10210(.A (n_103), .B (n_177), .Y (n_130));
  AOI211X1 g10194(.A0 (n_106), .A1 (n_79), .B0 (n_112), .C0 (n_88), .Y
       (n_180));
  NAND2XL g10220(.A (n_174), .B (n_125), .Y (n_152));
  NAND2XL g10191(.A (n_131), .B (n_140), .Y (n_147));
  OAI21X2 g10163(.A0 (n_67), .A1 (n_129), .B0 (n_100), .Y (n_193));
  OR2XL g10238(.A (n_127), .B (n_121), .Y (n_128));
  MXI2XL g10183(.A (n_123), .B (n_135), .S0 (n_122), .Y (n_124));
  NOR2BX1 g10222(.AN (n_121), .B (n_101), .Y (n_178));
  AOI31X1 g10232(.A0 (n_150), .A1 (n_74), .A2 (n_118), .B0 (n_96), .Y
       (n_170));
  OAI21X1 g10233(.A0 (n_127), .A1 (n_94), .B0 (n_150), .Y (n_196));
  AOI31X1 g10234(.A0 (n_134), .A1 (n_120), .A2 (n_80), .B0 (n_92), .Y
       (n_158));
  NAND2X1 g10206(.A (n_131), .B (n_119), .Y (n_143));
  OAI21X1 g10192(.A0 (n_81), .A1 (n_76), .B0 (n_123), .Y (n_137));
  NAND3X1 g10248(.A (n_221), .B (n_204), .C (n_118), .Y (n_138));
  OAI21X2 g10207(.A0 (n_132), .A1 (n_69), .B0 (n_144), .Y (n_145));
  OAI22X1 g10211(.A0 (n_150), .A1 (n_75), .B0 (n_174), .B1 (n_116), .Y
       (n_117));
  NOR2X1 g10209(.A (n_73), .B (n_86), .Y (n_115));
  AOI21X1 g10208(.A0 (n_113), .A1 (n_112), .B0 (n_89), .Y (n_114));
  AOI22X1 g10231(.A0 (n_280), .A1 (n_109), .B0 (n_108), .B1 (n_107), .Y
       (n_111));
  OA21X1 g10235(.A0 (n_220), .A1 (n_95), .B0 (n_23), .Y (n_183));
  SDFFRHQX1 \Sum_reg[1] (.RN (n_239), .CK (clk), .D (n_106), .SI
       (n_87), .SE (n_68), .Q (Sum[1]));
  NOR2XL g10257(.A (n_285), .B (n_105), .Y (n_121));
  OAI31X1 g10247(.A0 (n_144), .A1 (n_135), .A2 (n_155), .B0 (n_105), .Y
       (n_125));
  NAND3X1 g10249(.A (n_104), .B (n_174), .C (n_197), .Y (n_172));
  OAI21X1 g10212(.A0 (n_150), .A1 (n_279), .B0 (n_58), .Y (n_202));
  NOR2BXL g10219(.AN (n_102), .B (n_101), .Y (n_103));
  AOI2BB1X1 g10228(.A0N (n_51), .A1N (n_99), .B0 (n_98), .Y (n_100));
  NAND2XL g10221(.A (n_57), .B (n_118), .Y (n_171));
  NOR2X1 g10225(.A (n_97), .B (n_101), .Y (n_177));
  OAI21X1 g10215(.A0 (n_83), .A1 (n_66), .B0 (n_82), .Y (n_140));
  INVXL g10263(.A (n_95), .Y (n_96));
  AOI21X1 g10265(.A0 (n_134), .A1 (n_93), .B0 (n_285), .Y (n_94));
  SDFFRHQX1 \Sum_reg[0] (.RN (n_239), .CK (clk), .D (n_53), .SI (n_47),
       .SE (Cin_reg), .Q (Sum[0]));
  CLKINVX1 g10264(.A (n_102), .Y (n_92));
  NOR2XL g10260(.A (n_127), .B (n_279), .Y (n_159));
  INVXL g10171(.A (n_129), .Y (n_90));
  NOR2XL g10237(.A (n_77), .B (n_84), .Y (n_89));
  OAI21X1 g10230(.A0 (n_87), .A1 (n_85), .B0 (n_71), .Y (n_88));
  AOI21X1 g10227(.A0 (n_85), .A1 (n_78), .B0 (n_84), .Y (n_86));
  OAI21X1 g10224(.A0 (n_83), .A1 (n_55), .B0 (n_82), .Y (n_119));
  AOI21X1 g10214(.A0 (n_191), .A1 (n_46), .B0 (n_81), .Y (n_122));
  OAI21X1 g10266(.A0 (n_27), .A1 (n_131), .B0 (n_191), .Y (n_80));
  OAI21X1 g10246(.A0 (n_70), .A1 (n_41), .B0 (n_25), .Y (n_98));
  NOR2BX1 g10289(.AN (n_62), .B (n_280), .Y (n_107));
  AOI21X1 g10272(.A0 (A_reg[13]), .A1 (B_reg[13]), .B0 (n_278), .Y
       (n_95));
  NOR2BX1 g10287(.AN (n_134), .B (n_59), .Y (n_105));
  AOI21X1 g10274(.A0 (n_134), .A1 (n_135), .B0 (n_285), .Y (n_102));
  NAND3BX2 g10251(.AN (n_61), .B (n_104), .C (n_221), .Y (n_101));
  NAND2XL g10240(.A (n_78), .B (n_77), .Y (n_79));
  AOI211X1 g10218(.A0 (n_144), .A1 (n_82), .B0 (n_45), .C0 (n_155), .Y
       (n_76));
  NOR2XL g10239(.A (n_127), .B (n_74), .Y (n_75));
  OAI21X1 g10229(.A0 (n_72), .A1 (n_71), .B0 (n_70), .Y (n_73));
  NOR2BX1 g10236(.AN (n_82), .B (n_63), .Y (n_69));
  NOR2X1 g10292(.A (n_108), .B (n_280), .Y (n_118));
  AOI21X1 g10177(.A0 (n_106), .A1 (n_68), .B0 (n_33), .Y (n_129));
  NAND3X1 g10241(.A (n_42), .B (n_162), .C (n_113), .Y (n_67));
  AOI21X1 g10244(.A0 (n_26), .A1 (n_146), .B0 (n_54), .Y (n_66));
  INVXL g10253(.A (n_63), .Y (n_64));
  OAI21X1 g10270(.A0 (n_185), .A1 (n_108), .B0 (n_62), .Y (n_109));
  OR4XL g10252(.A (n_185), .B (n_61), .C (n_220), .D (n_108), .Y
       (n_189));
  INVXL g10293(.A (n_59), .Y (n_60));
  NAND2XL g10217(.A (n_108), .B (n_57), .Y (n_58));
  NAND2XL g10271(.A (n_56), .B (n_146), .Y (n_214));
  NAND2X1 g10273(.A (n_113), .B (n_106), .Y (n_84));
  CLKINVX1 g10309(.A (n_280), .Y (n_197));
  NOR2X1 g10254(.A (n_54), .B (n_146), .Y (n_55));
  NAND2BX1 g10267(.AN (n_20), .B (n_53), .Y (n_77));
  NOR2X1 g10256(.A (n_52), .B (n_83), .Y (n_63));
  NAND2XL g10259(.A (n_97), .B (n_150), .Y (n_116));
  NOR2XL g10261(.A (n_134), .B (n_285), .Y (n_74));
  NAND2XL g10262(.A (n_162), .B (n_113), .Y (n_99));
  OAI21X1 g10243(.A0 (n_30), .A1 (n_40), .B0 (n_51), .Y (n_112));
  NAND2XL g10291(.A (n_108), .B (n_150), .Y (n_153));
  CLKINVX1 g10278(.A (n_106), .Y (n_87));
  NOR2X1 g10299(.A (n_120), .B (n_49), .Y (n_59));
  OR2X1 g10300(.A (n_31), .B (n_49), .Y (n_93));
  CLKINVX1 g10296(.A (n_135), .Y (n_123));
  CLKINVX1 g10297(.A (n_155), .Y (n_191));
  INVXL g10277(.A (n_53), .Y (n_47));
  OAI21X1 g10245(.A0 (n_24), .A1 (n_45), .B0 (n_144), .Y (n_46));
  OAI21X1 g10242(.A0 (n_97), .A1 (n_39), .B0 (n_185), .Y (n_57));
  CLKINVX1 g10283(.A (n_113), .Y (n_72));
  CLKINVX1 g10298(.A (n_150), .Y (n_139));
  CLKINVX1 g10275(.A (n_220), .Y (n_221));
  CLKINVX1 g10285(.A (n_285), .Y (n_174));
  CLKINVX1 g10308(.A (n_42), .Y (n_43));
  CLKINVX1 g10281(.A (n_162), .Y (n_41));
  CLKINVX1 g10284(.A (n_83), .Y (n_56));
  OAI21X1 g10250(.A0 (n_8), .A1 (n_22), .B0 (n_19), .Y (n_68));
  CLKINVX1 g10295(.A (n_131), .Y (n_132));
  NAND2X2 g10314(.A (n_29), .B (n_283), .Y (n_106));
  NAND2X2 g10305(.A (n_120), .B (n_32), .Y (n_155));
  NAND2X2 g10304(.A (n_134), .B (n_35), .Y (n_135));
  NAND2BX1 g10310(.AN (n_34), .B (n_40), .Y (n_42));
  MXI2X1 g10311(.A (n_15), .B (A_reg[0]), .S0 (B_reg[0]), .Y (n_53));
  NOR2X1 g10301(.A (n_39), .B (n_38), .Y (n_104));
  OAI22X2 g10312(.A0 (B_reg[4]), .A1 (n_7), .B0 (A_reg[4]), .B1 (n_11),
       .Y (n_162));
  NOR2BX2 g10303(.AN (n_144), .B (n_45), .Y (n_131));
  NAND2BX2 g10302(.AN (n_38), .B (n_62), .Y (n_108));
  NOR2BX1 g10306(.AN (n_185), .B (n_39), .Y (n_150));
  CLKINVX1 g10320(.A (n_35), .Y (n_49));
  NAND2XL g10258(.A (n_34), .B (n_33), .Y (n_71));
  AOI22X2 g10313(.A0 (A_reg[6]), .A1 (n_16), .B0 (B_reg[6]), .B1
       (n_14), .Y (n_83));
  CLKINVX1 g10280(.A (n_204), .Y (n_184));
  OAI22X2 g10315(.A0 (B_reg[5]), .A1 (n_9), .B0 (A_reg[5]), .B1 (n_1),
       .Y (n_146));
  AOI22X2 g10318(.A0 (A_reg[14]), .A1 (n_13), .B0 (B_reg[14]), .B1
       (n_4), .Y (n_220));
  OAI22X2 g10316(.A0 (B_reg[3]), .A1 (n_2), .B0 (A_reg[3]), .B1 (n_6),
       .Y (n_113));
  CLKINVX1 g10338(.A (n_31), .Y (n_32));
  CLKINVX1 g10279(.A (n_33), .Y (n_30));
  OAI211X1 g10269(.A0 (B_reg[2]), .A1 (A_reg[2]), .B0 (A_reg[0]), .C0
       (B_reg[0]), .Y (n_85));
  NAND2X2 g10330(.A (n_5), .B (n_17), .Y (n_35));
  OAI211X1 g10268(.A0 (A_reg[0]), .A1 (B_reg[0]), .B0 (Cin_reg), .C0
       (A_reg[2]), .Y (n_78));
  CLKINVX1 g10286(.A (n_97), .Y (n_127));
  NAND2X1 g10326(.A (A_reg[1]), .B (n_12), .Y (n_29));
  INVXL g10322(.A (n_144), .Y (n_27));
  INVXL g10282(.A (n_25), .Y (n_26));
  CLKINVX1 g10321(.A (n_120), .Y (n_81));
  CLKINVX1 g10276(.A (n_54), .Y (n_52));
  CLKXOR2X1 g10319(.A (A_reg[15]), .B (B_reg[15]), .Y (n_204));
  NOR2XL g10324(.A (A_reg[6]), .B (B_reg[6]), .Y (n_24));
  NAND2XL g10340(.A (A_reg[14]), .B (B_reg[14]), .Y (n_23));
  NOR2XL g10343(.A (A_reg[0]), .B (B_reg[0]), .Y (n_22));
  NOR2BX1 g10346(.AN (A_reg[2]), .B (B_reg[2]), .Y (n_34));
  NOR2XL g10329(.A (A_reg[13]), .B (B_reg[13]), .Y (n_61));
  NOR2XL g10328(.A (A_reg[12]), .B (B_reg[12]), .Y (n_38));
  NAND2XL g10327(.A (B_reg[2]), .B (A_reg[2]), .Y (n_51));
  AND2X1 g10352(.A (B_reg[1]), .B (A_reg[1]), .Y (n_33));
  NOR2X1 g10331(.A (A_reg[7]), .B (B_reg[7]), .Y (n_45));
  NAND2X1 g10354(.A (A_reg[6]), .B (B_reg[6]), .Y (n_82));
  NAND2X2 g10337(.A (B_reg[10]), .B (A_reg[10]), .Y (n_97));
  NAND2X2 g10336(.A (B_reg[7]), .B (A_reg[7]), .Y (n_144));
  NAND2XL g10342(.A (Cin_reg), .B (B_reg[2]), .Y (n_20));
  NAND2XL g10350(.A (A_reg[0]), .B (B_reg[0]), .Y (n_19));
  NAND2XL g10341(.A (A_reg[15]), .B (B_reg[15]), .Y (n_18));
  NAND2BX1 g10345(.AN (A_reg[2]), .B (B_reg[2]), .Y (n_40));
  NAND2XL g10349(.A (A_reg[4]), .B (B_reg[4]), .Y (n_25));
  NAND2XL g10351(.A (A_reg[3]), .B (B_reg[3]), .Y (n_70));
  NOR2X1 g10344(.A (A_reg[8]), .B (B_reg[8]), .Y (n_31));
  CLKAND2X2 g10353(.A (B_reg[5]), .B (A_reg[5]), .Y (n_54));
  NOR2X1 g10332(.A (A_reg[11]), .B (B_reg[11]), .Y (n_39));
  NAND2X2 g10333(.A (B_reg[8]), .B (A_reg[8]), .Y (n_120));
  NAND2X1 g10355(.A (A_reg[12]), .B (B_reg[12]), .Y (n_62));
  NAND2X2 g10334(.A (A_reg[11]), .B (B_reg[11]), .Y (n_185));
  NAND2X2 g10335(.A (B_reg[9]), .B (A_reg[9]), .Y (n_134));
  CLKINVX1 g10356(.A (B_reg[9]), .Y (n_17));
  CLKINVX1 g10380(.A (A_reg[9]), .Y (n_5));
  DFFRHQX2 \B_reg_reg[9] (.RN (n_239), .CK (clk), .D (B[9]), .Q
       (B_reg[9]));
  DFFRHQX1 \A_reg_reg[8] (.RN (n_239), .CK (clk), .D (A[8]), .Q
       (A_reg[8]));
  DFFRHQX1 \B_reg_reg[8] (.RN (n_239), .CK (clk), .D (B[8]), .Q
       (B_reg[8]));
  DFFRHQX1 \A_reg_reg[12] (.RN (n_239), .CK (clk), .D (A[12]), .Q
       (A_reg[12]));
  DFFRHQX2 \B_reg_reg[7] (.RN (n_239), .CK (clk), .D (B[7]), .Q
       (B_reg[7]));
  DFFRHQX1 \B_reg_reg[10] (.RN (n_239), .CK (clk), .D (B[10]), .Q
       (B_reg[10]));
  DFFRHQX1 \A_reg_reg[13] (.RN (n_239), .CK (clk), .D (A[13]), .Q
       (A_reg[13]));
  DFFRHQX1 \B_reg_reg[13] (.RN (n_239), .CK (clk), .D (B[13]), .Q
       (B_reg[13]));
  DFFRHQX1 \B_reg_reg[2] (.RN (n_239), .CK (clk), .D (B[2]), .Q
       (B_reg[2]));
  DFFRHQX2 \A_reg_reg[7] (.RN (n_239), .CK (clk), .D (A[7]), .Q
       (A_reg[7]));
  DFFRHQX1 \A_reg_reg[10] (.RN (n_239), .CK (clk), .D (A[10]), .Q
       (A_reg[10]));
  DFFRHQX1 \A_reg_reg[15] (.RN (n_239), .CK (clk), .D (A[15]), .Q
       (A_reg[15]));
  DFFRHQX1 \B_reg_reg[12] (.RN (n_239), .CK (clk), .D (B[12]), .Q
       (B_reg[12]));
  DFFRHQX1 \B_reg_reg[15] (.RN (n_239), .CK (clk), .D (B[15]), .Q
       (B_reg[15]));
  DFFRHQX2 \A_reg_reg[11] (.RN (n_239), .CK (clk), .D (A[11]), .Q
       (A_reg[11]));
  DFFRHQX1 \A_reg_reg[9] (.RN (n_239), .CK (clk), .D (A[9]), .Q
       (A_reg[9]));
  DFFRHQX1 \B_reg_reg[11] (.RN (n_239), .CK (clk), .D (B[11]), .Q
       (B_reg[11]));
  DFFRHQX1 \A_reg_reg[1] (.RN (n_239), .CK (clk), .D (A[1]), .Q
       (A_reg[1]));
  DFFRHQX2 \B_reg_reg[0] (.RN (n_239), .CK (clk), .D (B[0]), .Q
       (B_reg[0]));
  DFFRHQX1 \A_reg_reg[2] (.RN (n_239), .CK (clk), .D (A[2]), .Q
       (A_reg[2]));
  INVXL g10407(.A (reset), .Y (n_239));
  MXI2XL g2(.A (n_211), .B (n_203), .S0 (n_225), .Y (n_275));
  MXI2XL g10458(.A (n_212), .B (n_216), .S0 (n_228), .Y (n_276));
  OAI21X1 g10459(.A0 (n_178), .A1 (n_177), .B0 (n_184), .Y (n_277));
  AOI21X1 g10460(.A0 (n_282), .A1 (n_281), .B0 (n_62), .Y (n_278));
  DFFRX1 \B_reg_reg[6] (.RN (n_239), .CK (clk), .D (B[6]), .Q
       (B_reg[6]), .QN (n_16));
  NAND2BX1 g10514(.AN (n_108), .B (n_185), .Y (n_279));
  AND2X1 g10515(.A (n_281), .B (n_282), .Y (n_280));
  NAND2BX1 g10516(.AN (A_reg[13]), .B (B_reg[13]), .Y (n_281));
  NAND2BX1 g10517(.AN (B_reg[13]), .B (A_reg[13]), .Y (n_282));
  NAND2BX1 g10518(.AN (A_reg[1]), .B (B_reg[1]), .Y (n_283));
  AND3XL g10519(.A (n_125), .B (n_104), .C (n_174), .Y (n_284));
  OAI21X2 g10520(.A0 (A_reg[10]), .A1 (B_reg[10]), .B0 (n_97), .Y
       (n_285));
  DFFRX1 \A_reg_reg[0] (.RN (n_239), .CK (clk), .D (A[0]), .Q
       (A_reg[0]), .QN (n_15));
  DFFRX1 \A_reg_reg[6] (.RN (n_239), .CK (clk), .D (A[6]), .Q
       (A_reg[6]), .QN (n_14));
  DFFRX1 \B_reg_reg[14] (.RN (n_239), .CK (clk), .D (B[14]), .Q
       (B_reg[14]), .QN (n_13));
  DFFRX1 \B_reg_reg[1] (.RN (n_239), .CK (clk), .D (B[1]), .Q
       (B_reg[1]), .QN (n_12));
  DFFRX1 \B_reg_reg[4] (.RN (n_239), .CK (clk), .D (B[4]), .Q
       (B_reg[4]), .QN (n_11));
  DFFRX1 \A_reg_reg[5] (.RN (n_239), .CK (clk), .D (A[5]), .Q
       (A_reg[5]), .QN (n_9));
  DFFRX1 Cin_reg_reg(.RN (n_239), .CK (clk), .D (Cin), .Q (Cin_reg),
       .QN (n_8));
  DFFRX1 \A_reg_reg[4] (.RN (n_239), .CK (clk), .D (A[4]), .Q
       (A_reg[4]), .QN (n_7));
  DFFRX1 \B_reg_reg[3] (.RN (n_239), .CK (clk), .D (B[3]), .Q
       (B_reg[3]), .QN (n_6));
  DFFRX1 \A_reg_reg[14] (.RN (n_239), .CK (clk), .D (A[14]), .Q
       (A_reg[14]), .QN (n_4));
  DFFRX1 \A_reg_reg[3] (.RN (n_239), .CK (clk), .D (A[3]), .Q
       (A_reg[3]), .QN (n_2));
  DFFRX1 \B_reg_reg[5] (.RN (n_239), .CK (clk), .D (B[5]), .Q
       (B_reg[5]), .QN (n_1));
endmodule

